---
title: "k_optimization"
author: "Antonio Jesús Balboa Ortega"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
require(tidyverse)
require(vegan)
require(dplyr)
require(purrr)
require(ggupset)
require(tibble)
require(Biostrings)
require(pwalign)
require(BiocGenerics)
# Seed
set.seed(26)
```

```{r}
set.seed(26)
# opcional para no correr de nuevo DADA2
OTU_table <- read.csv("ASV_table.csv")
rownames(ASV_table) <- ASV_table$X
ASV_table$X <- NULL

# Delete samples with low reads
depths <- rowSums(ASV_table)
summary(depths)
sort(depths)

# load modified species taxonomy for species
taxonomy_mod_100 <- read.csv("taxonomia_100.csv")

# Create OTU table
sequences <- colnames(ASV_table)

asv_ids <- paste0("ASV", seq_along(sequences))

# Dictionary for storing sequences and taxa
seq_dict <- data.frame(
  ASV = asv_ids,
  Sequence =  sequences,
  taxa = taxonomy_mod_100$Genus_Species,
  Genus = taxonomy_mod_100$Genus,
  stringsAsFactors = FALSE)


colnames(ASV_table) <- asv_ids

OTU_table_filt <- ASV_table[depths>10000, ]

# Delete singletons
singleton_threshold <- 11 

asv_totals <- colSums(OTU_table_filt)
table(asv_totals < singleton_threshold)
n_singletons <- sum(asv_totals < singleton_threshold)

cat("ASVs con < ", singleton_threshold, " lecturas (a eliminar): ", n_singletons, "\n")

ASVs_to_keep <- names(asv_totals)[asv_totals >= singleton_threshold]
OTU_table_filt <- OTU_table_filt[, ASVs_to_keep, drop = FALSE]
```

```{r ground truth, include=FALSE}

# Defining ground truth

ground_truth_sequences <- data.frame(
  Bacteria = c("Bacillus licheniformis BT_1B_CT2","Bifidobacterium longum 12_1_47 B FAA","Rothia mucilaginosa ATCC 25296","Parvimonas micra ATCC 33270","Mogibacterium timidum ATCC 33093","Campylobacter concisus 10_1_50","Eggerthella lenta MR1 12","Slackia exigua ATCC 700122","klebsiella variicola 1_1_55","Fusobacterium periodonticum D10","Leptotrichia goodfellowii D28","Weisella cibaria kACC 11862","Eikenella corrodens CC82I","Neisseria pneumonie GT 4A CT1","Tannerella sp. 6_1_58 FAA CT1","Hoylesella oralis CC98A","Capnocytophaga sputigena ATCC 33612","Granulicatella adiacens ATCC 49175","Streptococcus gordonii 2_1_36 FAA","Gemella morbillorum M424","Dialister pneumosintes KCOM 1685","Veionella sp. 3_1_44","Coprobacillus cateniformis 29_1","Bifidobacterium angulatum JCM 7096","Collinsella aerofaciens 4_8_47 FAA","Bilophila wadsworthia 3_1_6","Escherichia coli 1_1_43","Fusobacterium gonidiaformans 3_1_5R","Fusobacterium ulcerans 12_1B","Anaerostipes hadrus ATCC 29173","Enterocloster bolteae 90A9","Lactobacillus iners 7_1_47 FAA","Pediococcus acidilactici 7_4A","Ralstonia pickettii 5_7_47 FAA","Paenibacillus barengoltzii G22","Parabacteroides merdae ATCC 43184","Bacteroides caccae CL03T12C61","Cutibacterium acnes NBRC 107605","Alistipes shahii WAL 8301","Subdoligranulum sp. 4_3_54A2FAA","Enterococcus saccharolyticus 30_1","Synergistes sp. 22_5_S_12_D6 FAA"),
  Sequence = c("ATACGTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGCGCGCGCAGGCGGTTTCTTAAGTCTGATGTGAAAGCCCCCGGCTCAACCGGGGAGGGTCATTGGAAACTGGGGAACTTGAGTGCAGAAGAGGAGAGTGGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAACACCAGTGGCGAAGGCGACTCTCTGGTCTGTAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCGAACAGG",
               "TACGTAGGGTGCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGCTCGTAGGCGGTTCGTCGCGTCCGGTGTGAAAGTCCATCGCTTAACGGTGGATCCGCGCCGGGTACGGGCGGGCTTGAGTGCGGTAGGGGAGACTGGAATTCCCGGTGTAACGGTGGAATGTGTAGATATCGGGAAGAACACCAATGGCGAAGGCAGGTCTCTGGGCCGTTACTGACGCTGAGGAGCGAAAGCGTGGGGAGCGAACAGGA",
               "TACGTAGGGCGCGAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCTTGTAGGCGGTTTGTCGCGTCTGCTGTGAAAGGCCGGAGCTTAACTCCGTGTATTGCAGTGGGTACGGGCAGACTAGAGTGCAGTAGGGGAGACTGGAACTCCTGGTGTAGCGGTGGAATGCGCAGATATCAGGAAGAACACCGATGGCGAAGGCAGGTCTCTGGGCTGTAACTGACGCTGAGAAGCGAAAGCATGGGGAGCGAACAGG",
               "TACGTATGGGGCGAGCGTTGTCCGGAATTATTGGGCGTAAAGGGTACGTAGGCGGTTTTTTAAGTCAGGTGTGAAAGCGTGAGGCTTAACCTCATTAAGCACTTGAAACTGGAAGACTTGAGTGAAGGAGAGGAAAGTGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAATACCGGTGGCGAAGGCGACTTTCTGGACTTTTACTGACGCTCAGGTACGAAAGCGTGGGGAGCAAACAGGAT",
               "TACGTAGGGGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGTGCGTAGGTGGTTACCTAAGCGCAAGGTTTAAATTAGAGGCTCAACCTCTACATGCCTTGCGAACTGGGCTACTTGAGTGCAGGAGGGGAAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCGGCGGCGAAGGCGGCTTTCTGGACTGTAACTGACACTGAGGCACGAAAGCGTGGGTAGCAAACAGGAT",
               "TACGGAGGGTGCAAGCGTTACTCGGAATCACTGGGCGTAAAGGACGCGTAGGCGGATTATCAAGTCTCTTGTGAAATCCTATGGCTTAACCATAGAACTGCTTGGGAAACTGATAATCTAGAGTGAGGGAGAGGCAGATGGAATTGGTGGTGTAGGGGTAAAATCCGTAGAGATCACCAGGAATACCCATTGCGAAGGCGATCTGCTGGAACTCAACTGACGCTAATGCGTGAAAGCGTGGGGAGCAAACAGGA",
               "AATACGTAGGGAGCGAGCGTTATCCGGATTCATTGGGCGTAAAGAGCGCGTAGGCGGCCTCTCAAGCGGGATCTCTAATCCGAGGGCTCAACCCCCGGCCGGATCCCGAACTGGGAGGCTCGAGTTCGGTAGAGGCAGGCGGAATTCCCGGTGTAGCGGTGGAATGCGCAGATATCGGGAAGAACACCGATGGCGAAGGCAGCCTGCTGGGCCGCAACTGACGCTGAGGCGCGAAAGCTAGGGGAGCGAACAGG",
               "ATACGTAGGGGGCGAGCGTTATCCGGATTCATTGGGCGTAAAGCGCGCGCAGGCGGCCCGCCAAGCGGCCTCGTCGAAGCCGGGGGCTCAACCCCCGGAAGCGACCCGAACTGGCGGGCTCGAGTGGGGCAGGGGAGGATGGAATTCCCGGTGTAGCGGTGAAATGCGCAGATATCGGGAGGAACACCGACGGCGAAGGCAGCCCTCTGGGCCTTCACTGACGCTGAGGCGCGAAAGCTGGGGGAGCGAACAGG",
               "TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTCAAGTCGGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATTCGAAACTGGCAGGCTAGAGTCTTGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGA",
               "AATACGTATGTCACAAGCGTTATCCGGATTTATTGGGCGTAAAGCGCGTCTAGGTGGTTATGTAAGTCTGATGTGAAAATGCAGGGCTCAACTCTGTATTGCGTTGGAAACTGCATGACTAGAGTACTGGAGAGGTAAGCGGAACTACAAGTGTAGAGGTGAAATTCGTAGATATTTGTAGGAATGCCGATGGGGAAGCCAGCTTACTGGACAGATACTGACGCTAAAGCGCGAAAGCGTGGGTAGCAAACAGG",
               "TACGTATGTCGCGAGCGTTATCCGGAATTATTGGGCATAAAGGGCATCTAGGCGGACGATCAAGTCAGGGGTGAAAACTTGCGGCTCAACTGTAAGCTTGCCTTTGAAACTGATTGTCTAGAGTATTGGAAAGGTGGGCGGAACTACACGAGTAGAGGTGAAATTCGTAGATATGTGTAGGAATGCCGATGATGAAGATAGCTCACTGGACGATAACTGACGCTGAAGTGCGAAAGCTAGGGGAGCGAACAGGA",
               "TACGTATGTTCCAAGCGTTATCCGGATTTATTGGGCGTAAAGCGAGCGCAGACGGTTATTTAAGTCTGAAGTGAAAGCCCTCAGCTCAACTGAGGAATTGCTTTGGAAACTGGATGACTTGAGTGCAGTAGAGGAAAGTGGAACTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAAGAACACCAGTGGCGAAGGCGGCTTTCTGGACTGTAACTGACGTTGAGGCTCGAAAGTGTGGGTAGCAAACAGGA",
               "TACGTAGGGTGCGAGCGTTAATCGGAATTACTGGGCGTAAAGCGAGCGCAGACGGTTATTTAAGCAGGATGTGAAATCCCCGGGCTTAACCTGGGAACTGCGTTCTGAACTGGATAGCTAGAGTGTGTCAGAGGGGGGTAGAATTCCACGTGTAGCAGTGAAATGCGTAGAGATGTGGAGGAATACCGATGGCGAAGGCAGCCCCCTGGGATAACACTGACGTTCATGCTCGAAAGCGTGGGTAGCAAACAGGA",
               "TACGTAGGGTGCGAGCGTTAATCGGAATTACTGGGCGTAAAGCGGGCGCAGACGGTTACTTAAGCAGGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCGTTCTGAACTGGGTGACTAGAGTGTGTCAGAGGGAGGTAGAATTCCACGTGTAGCAGTGAAATGCGTAGAGATGTGGAGGAATACCGATGGCGAAGGCAGCCTCCTGGGATAACACTGACGTTCATGCCCGAAAGCGTGGGTAGCAAACAGGA",
               "CGCGGTAATACGGAAGATGCGAGCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGAAGGATAAGTCAGCGGTGAAATGCATTCAGCTCAACTGGAGAATTGCCGATGAAACTGTTTTTCTAGAGTATAAAAGAGGTATGCGGAATGCGTGGTGTAGCGGTGAAATGCATAGATATCACGCAGAACCCCGATTGCGAAGGCAGCATACTGGGCTATAACTGACGCTGAAGCACGAAAGCGTGGGTATCGAACAGG",
               "TACGGAAGGTCCGGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCAGTTTTTTAAGCGTGCTGTGAAATGTACCGGCTCAACCGGTGATGTGCAGCGCGAACTGGGAATCTTGAGTACGCAGTAAGCAGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATTGCGTAGGCAGCTTGCTGTAGCGTAACTGACGCTGAAGCTCGAAAGTGCGGGTATCGAACAGGA",
               "TACGGAGGATGCGAGCGTTATCCGGAATCATTGGGTTTAAAGGGTCCGTAGGCGGGCTGATAAGTCAGAGGTGAAAGCGCTTAGCTCAACTAAGCAACTGCCTTTGAAACTGTCAGTCTTGAATGATTGTGAAGTAGTTGGAATGTGTAGTGTAGCGGTGAAATGCTTAGATATTACACAGAACACCGATAGCGAAGGCATATTACTAACAATTTATTGACGCTGATGGACGAAAGCGTGGGGAGCGAACAGGA",
               "TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTCCTTAAGTCTGATGTGAAAGCCCCCGGCTCAACCGGGGAGGGTCATTGGAAACTGGGGAACTTGAGTGCAGAAGAGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCAGTGGCGAAGGCGACTCTCTGGTCTGTAACTGACGCTGAGGCTCGAAAGCGTGGGTAGCAAACAGGA",
               "TACGTAGGTCCCGAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTAGATAAGTCTGAAGTTAAAGGCTGTGGCTTAACCATAGTACGCTTTGGAAACTGTTTAACTTGAGTGCAGAAGGGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCGGTGGCGAAAGCGGCTCTCTGGTCTGTAACTGACGCTGAGGCTCGAAAGCGTGGGGAGCGAACAGGAT",
               "ATACGTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGCGCGCGCAGGTGGTTTAATAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGTTAAACTTGAGTGCAGGAGAGAAAAGTGGAATTCCTAGTGTAGCGGTGAAATGCGTAGAGATTAGGAGGAACACCAGTGGCGAAGGCGGCTTTTTGGCCTGTAACTGACACTGAGGCGCGAAAGCGTGGGGAGCAAACAGG",
               "TACGTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGCGCGCGCAGGCGGCTTCTTAAGTCCATCTTAAAAGCGTGGGGCTCAACCCCATGAGGGGATGGAAACTGGGAAGCTGGAGTATCGGAGAGGAAAGTGGAATTCCTAGTGTAGCGGTGAAATGCGTAGAGATTAGGAAGAACACCGGTGGCGAAGGCGACTTTCTAGACGAAAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGGAT",
               "TACGTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGCGCGCGCAGGCGGATAGGTCAGTCTGTCTTAAAAGTTCGGGGCTTAACCCCGTGATGGGATGGAAACTGCCAATCTAGAGTATCGGAGAGGAAAGTGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAAGAACACCAGTGGCGAAGGCGACTTTCTGGACGAAAACTGACGCTGAGGCGCGAAAGCCAGGGGAGCGAACGGGAT",
               "TACGTAGGTGGCGAGCGTTATCCGGAATCATTGGGCGTAAAGAGGGAGCAGGCGGCAATAGAGGTCTGCGGTGAAAGCCTGAAGCTAAACTTCAGTAAGCCGTGGAAACCAAATAGCTAGAGTGCAGTAGAGGATCGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCAGTGGCGAAGGCGACGATCTGGGCTGCAACTGACGCTCAGTCCCGAAAGCGTGGGGAGCAAATAGGAT",
               "TACGTAGGGTGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGCTCGTAGGCGGTTCGTCGCGTCCGGTGTGAAAGTCCATCGCTTAACGGTGGATCTGCGCCGGGTACGGGCGGGCTGGAGTGCGGTAGGGGAGACTGGAATTCCCGGTGTAACGGTGGAATGTGTAGATATCGGGAAGAACACCAATGGCGAAGGCAGGTCTCTGGGCCGTTACTGACGCTGAGGAGCGAAAGCGTGGGGAGCGAACAGGA",
               "TACGTAGGGGGCGAGCGTTATCCGGATTCATTGGGCGTAAAGCGCGCGTAGGCGGCCCGGCAGGCCGGGGGTCGAAGCGGGGGGCTCAACCCCCCGAAGCCCCCGGAACCTCCGCGGCTTGGGTCCGGTAGGGGAGGGTGGAACACCCGGTGTAGCGGTGGAATGCGCAGATATCGGGTGGAACACCGGTGGCGAAGGCGGCCCTCTGGGCCGAGACCGACGCTGAGGCGCGAAAGCTGGGGGAGCGAACAGGA",
               "TACGGAGGGTGCAAGCGTTAATCGGAATCACTGGGCGTAAAGCGCACGTAGGCGGCTTGGTAAGTCAGGGGTGAAATCCCACAGCCCAACTGTGGAACTGCCTTTGATACTGCCAGGCTTGAGTACCGGAGAGGGTGGCGGAATTCCAGGTGTAGGAGTGAAATCCGTAGATATCTGGAGGAACACCGGTGGCGAAGGCGGCCACCTGGACGGTAACTGACGCTGAGGTGCGAAAGCGTGGGTAGCAAACAGGA",
               "ATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGG",
               "AATACGTATGTCGCAAGCGTTATCCGGATTTATTGGGCGTAAAGCGCGTCTAGGCGGCAAGGAAAGTCTGATGTGAAAATGCGGGGCTCAACTCCGTATTGCGTTGGAAACTGCCTTACTAGAGTACTGGAGAGGTAGGCGGAACTACAAGTGTAGAGGTGAAATTCGTAGATATTTGTAGGAATGCCGATGGGGAAGCCAGCTACTGGACAGATACTGACGCTAAAGCGCGAAAGCGTGGGTAGCAAACAGG",
               "TACGTATGTCGCAAGCGTTATCCGGATTTATTGGGCGTAAAGCGCGTCTAGGCGGCAAGGAAAGTCTGATGTGAAAATGCGGGGCTCAACTCCGTATTGCGTTGGAAACTGCCTTACTAGAGTACTGGAGAGGTAGGCGGAACTACAAGTGTAGAGGTGAAATTCGTAGATATTTGTAGGAATGCCGATGGGGAAGCCAGCCTACTGGACAGATACTGACGCTAAAGCGCGAAAGCGTGGGTAGCAAACAGGAT",
               "TACGTAGGGGGCAAGCGTTATCCGGAATTACTGGGTGTAAAGGGTGCGTAGGTGGTATGGCAAGTCAGAAGTGAAAACCCAGGGCTTAACTCTGGGACTGCTTTTGAAACTGTCAGACTGGAGTGCAGGAGAGGTAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACATCAGTGGCGAAGGCGGCTTACTGGACTGAAACTGACACTGAGGCACGAAAGCGTGGGGAGCAAACAGGA",
               "TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCGAAGCAAGTCTGAAGTGAAAACCCAGGGCTCAACCCTGGGACTGCTTTGGAAACTGTTTTGCTAGAGTGTCGGAGAGGTAAGTGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTGGCGAAGGCGGCTTACTGGACGATAACTGACGTTGAGGCTCGAAAGCGTGGGGAGCAAACGCAG",
               "ACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGTGCAGGCGGCTCGATAAGTCTGATGTGAAAGCCTTCGGCTCAACCGGAGAATTGCATCAGAAACTGTCGAGCTTGAGTACAGAAGAGGAGAGTGGAACTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAAGAACACCGGTGGCGAAGGCGGCTCTCTGGTCTGTTACTGACGCTGAGGCTCGAAAGCATGGGTAGCGAACAGGAT",
               "ACGTAGGTGGCAAGCGTTATCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTCTTTTAAGTCTAATGTGAAAGCCTTCGGCTCAACCGAAGAAGTGCATTGGAAACTGGGAGACTTGAGTGCAGAAGAGGACAGTGGAACTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAAGAACACCAGTGGCGAAGGCGGCTGTCTGGTCTGTAACTGACGCTGAGGCTCGAAAGCATGGGTAGCGAACAGGAT",
               "TACGTAGGGTCCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGTGCGCAGGCGGTTGTGCAAGACCGATGTGAAATCCCCGAGCTTAACTTGGGAATTGCATTGGTGACTGCACGGCTAGAGTGTGTCAGAGGGGGGTAGAATTCCACGTGTAGCAGTGAAATGCGTAGAGATGTGGAGGAATACCGATGGCGAAGGCAGCCCCCTGGGATAACACTGACGCTCATGCACGAAAGCGTGGGGAGCAAACAGGA",
               "TACGTAGGGGGCGAGCGTTGTCCGGAATTATTGGGCGTAAAGCGCGCGCAGGCGGCTGTTTAAGTCTGGTGTTTAATCCTGGGGCTCAACCCCGGGTCGCACTGGAAACTGGGCAGCTTGAGTGCAGAAGAGGAGAGTGGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAACACCAGTGGCGAAGGCGACTCTCTGGGCTGTAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGGAT",
               "TACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGTGGTGATTTAAGTCAGCGGTGAAAGTTTGTGGCTCAACCATAAAATTGCCGTTGAAACTGGGTTACTTGAGTGTGTTTGAGGTAGGCGGAATGCGTGGTGTAGCGGTGAAATGCATAGATATCACGCAGAACTCCGATTGCGAAGGCAGCTTACTAAACCATAACTGACACTGAAGCACGAAAGCGTGGGGATCAAACAGGA",
               "TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGATTGTTAAGTCAGTTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGATACTGGCAGTCTTGAGTGCAGTAGAGGTGGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATTGCGAAGGCAGCTCACTGGAGTGTAACTGACGCTGATGCTCGAAAGTGTGGGTATCAAACAGGA",
               "TACGTAGGGTGCGAGCGTTGTCCGGATTTATTGGGCGTAAAGGGCTCGTAGGTGGTTGATCGCGTCGGAAGTGTAATCTTGGGGCTTAACCCTGAGCGTGCTTTCGATACGGGTTGACTTGAGGAAGGTAGGGGAGAATGGAATTCCTGGTGGAGCGGTGGAATGCGCAGATATCAGGAGGAACACCAGTGGCGAAGGCGGTTCTCTGGGCCTTTCCTGACGCTGAGGAGCGAAAGCGTGGGGAGCGAACAGGC",
               "TACGGAGGATCCAAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGTTTGATAAGTTAGAGGTGAAATACCGGTGCTTAACACCGGAACTGCCTCTAATACTGTTGAACTAGAGAGTAGTTGCGGTAGGCGGAATGTATGGTGTAGCGGTGAAATGCTTAGAGATCATACAGAACACCGATTGCGAAGGCAGCTTACCAAACTATATCTGACGTTGAGGCACGAAAGCGTGGGGAGCAAACAGGA",
               "AACGTAGGGTGCAAGCGTTGTCCGGAATTACTGGGTGTAAAGGGAGCGCAGGCGGATTGGCAAGTTGGGAGTGAAATCTATGGGCTCAACCCATAAATTGCTTTCAAAACTGTCAGTCTTGAGTGGTGTAGAGGTAGGCGGAATTCCCGGTGTAGCGGTGGAATGCGTAGATATCGGGAGGAACACCAGTGGCGAAGGCGGCCTACTGGGCACTAACTGACGCTGAGGCTCGAAAGCATGGGTAGCAAACCTCA",
               "ACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTTCTTAAGTCTGATGTGAAAGCCCCCGGCTCAACCGGGGAGGGTCATTGGAAACTGGGAGACTTGAGTGCAGAAGAGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCAGTGGCGAAGGCGGCTCTCTGGTCTGTAACTGACGCTGAGGCTCGAAAGCGTGGGGAGCGAACAGGAT",
               "TACGTAGGGGGCGAGCGTTGTTCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGACCAGTAAGTCTGTCGTCAAAGGCGGAGGCTCAACCTTCGTTCCACGATAGATACTGCGGGTCTAGAGTATGTGAGAGGGAAGTGGAATTCCCGGTGTAGCGGTGAAATGCGTAGATATCGGGAGGAACACCAGTGGCGAAGGCGGCTTCCTGGCACACAACTGACGCTCATGTGCGAAAGCCAGGGCAGCGAACGGGA"))


ground_truth_taxa <- list(species = c("Bacillus_licheniformis","Bifidobacterium_longum","Rothia_mucilaginosa","Parvimonas_micra","Mogibacterium_timidum","Campylobacter_concisus","Eggerthella_lenta","Slackia_exigua","klebsiella_variicola","Fusobacterium_periodonticum","Leptotrichia_goodfellowii","Weisella_cibaria","Eikenella_corrodens","Neisseria_mucosa","Tannerella_sp","Prevotella_oralis","Capnocytophaga_sputigena","Granulicatella_adiacens","Streptococcus_gordonii","Gemella_morbillorum","Dialister_pneumosintes","Veionella_parvula","Coprobacillus_cateniformis","Bifidobacterium_angulatum","Collinsella_aerofaciens","Bilophila_wadsworthia","Escherichia_coli","Fusobacterium_gonidiaformans","Fusobacterium_varium","Fusobacterium_ulcerans","Anaerostipes_hadrus","Enterocloster_bolteae","Lactobacillus_iners","Pediococcus_acidilactici","Ralstonia_pickettii","Paenibacillus_barengoltzii","Parabacteroides_merdae","Bacteroides_caccae","Cutibacterium_acnes","Alistipes_shahii","Subdoligranulum_variabile","Enterococcus_saccharolyticus","Synergistes_sp."), genus = c("Bacillus","Bifidobacterium","Rothia","Parvimonas","Mogibacterium","Campylobacter","Eggerthella","Slackia","klebsiella","Fusobacterium","Leptotrichia","Weisella","Eikenella","Neisseria","Tannerella","Prevotella","Hoylesella","Capnocytophaga","Granulicatella","Streptococcus","Gemella","Dialister","Veionella","Coprobacillus","Collinsella","Bilophila","Escherichia","Escherichia/Shigella","Fusobacterium","Anaerostipes","Clostridium","Lactobacillus","Pediococcus","Ralstonia","Paenibacillus","Parabacteroides","Bacteroides","Propionibacterium","Cutibacterium","Alistipes","Subdoligranulum","Enterococcus","Synergistes"))

OTU_table_filt_df <- data.frame(OTU_table_filt)
```

```{r filter standard(0.00005) pairwaise}
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_especies_standard_05_05 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.5,
  beta = 0.5,
  mode ="taxonomy"
)
# Results
k_especies_standard_05_05_df <- k_especies_standard_05_05$df_results

# plot
plot_especies_standard_05_05 <- plot_k2(k_especies_standard_05_05)

# alpha = 0.6 and beta = 0.4
k_especies_standard_06_04 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.6,
  beta = 0.4,
  mode ="taxonomy"
)
# Results
k_especies_standard_06_04_df <- k_especies_standard_06_04$df_results

# plot
plot_especies_standard_06_04 <- plot_k2(k_especies_standard_06_04)

# alpha = 0.7 and beta = 0.3
k_especies_standard_07_03 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.7,
  beta = 0.3,
  mode ="taxonomy"
)
# Results
k_especies_standard_07_03_df <- k_especies_standard_07_03$df_results

# plot
plot_especies_standard_07_03 <- plot_k2(k_especies_standard_07_03)

# alpha = 0.8 and beta = 0.2
k_especies_standard_08_02 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.8,
  beta = 0.2,
  mode ="taxonomy"
)
# Results
k_especies_standard_08_02_df <- k_especies_standard_08_02$df_results

# plot
plot_especies_standard_08_02 <- plot_k2(k_especies_standard_08_02)

# alpha = 0.9 and beta = 0.1
k_especies_standard_09_01 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.9,
  beta = 0.1,
  mode ="taxonomy"
)
# Results
k_especies_standard_09_01_df <- k_especies_standard_09_01$df_results

# plot
plot_especies_standard_09_01 <- plot_k2(k_especies_standard_09_01)

# alpha = 1 and beta = 0
k_especies_standard_1_0 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 1,
  beta = 0,
  mode ="taxonomy"
)
# Results
k_especies_standard_1_0_df <- k_especies_standard_1_0$df_results

# plot
plot_especies_standard_1_0 <- plot_k2(k_especies_standard_1_0)

# alpha = 0.4 and beta = 0.6
k_especies_standard_04_06 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.4,
  beta = 0.6,
  mode ="taxonomy"
)
# Results
k_especies_standard_04_06_df <- k_especies_standard_04_06$df_results

# plot
plot_especies_standard_04_06 <- plot_k2(k_especies_standard_04_06)

# alpha = 0.3 and beta = 0.7
k_especies_standard_03_07 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.3,
  beta = 0.7,
  mode ="taxonomy"
)
# Results
k_especies_standard_03_07_df <- k_especies_standard_03_07$df_results

# plot
plot_especies_standard_03_07 <- plot_k2(k_especies_standard_03_07)

# alpha = 0.2 and beta = 0.8
k_especies_standard_02_08 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.2,
  beta = 0.8,
  mode ="taxonomy"
)
# Results
k_especies_standard_02_08_df <- k_especies_standard_02_08$df_results

# plot
plot_especies_standard_02_08 <- plot_k2(k_especies_standard_02_08)

# alpha = 0.1 and beta = 0.9
k_especies_standard_01_09 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.1,
  beta = 0.9,
  mode ="taxonomy"
)
# Results
k_especies_standard_01_09_df <- k_especies_standard_01_09$df_results

# plot
plot_especies_standard_01_09 <- plot_k2(k_especies_standard_01_09)

# alpha = 0 and beta = 1
k_especies_standard_0_1 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0,
  beta = 1,
  mode ="taxonomy"
)
# Results
k_especies_standard_0_1_df <- k_especies_standard_0_1$df_results

# plot
plot_especies_standard_0_1 <- plot_k2(k_especies_standard_0_1)


#SEQUENCES APPROACH
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_sequences_standard_05_05 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.5,
  beta = 0.5,
  mode ="sequence"
)
# Results
k_sequences_standard_05_05_df <- k_sequences_standard_05_05$df_results

# plot
plot_sequences_standard_05_05 <- plot_k2(k_sequences_standard_05_05)

# alpha = 0.6 and beta = 0.4
k_sequences_standard_06_04 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.6,
  beta = 0.4,
  mode ="sequence"
)
# Results
k_sequences_standard_06_04_df <- k_sequences_standard_06_04$df_results

# plot
plot_sequences_standard_06_04 <- plot_k2(k_sequences_standard_06_04)

# alpha = 0.7 and beta = 0.3
k_sequences_standard_07_03 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.7,
  beta = 0.3,
  mode ="sequence"
)
# Results
k_sequences_standard_07_03_df <- k_sequences_standard_07_03$df_results

# plot
plot_sequences_standard_07_03 <- plot_k2(k_sequences_standard_07_03)

# alpha = 0.8 and beta = 0.2
k_sequences_standard_08_02 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.8,
  beta = 0.2,
  mode ="sequence"
)
# Results
k_sequences_standard_08_02_df <- k_sequences_standard_08_02$df_results

# plot
plot_sequences_standard_08_02 <- plot_k2(k_sequences_standard_08_02)

# alpha = 0.9 and beta = 0.1
k_sequences_standard_09_01 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.9,
  beta = 0.1,
  mode ="sequence"
)
# Results
k_sequences_standard_09_01_df <- k_sequences_standard_09_01$df_results

# plot
plot_sequences_standard_09_01 <- plot_k2(k_sequences_standard_09_01)

# alpha = 1 and beta = 0
k_sequences_standard_1_0 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 1,
  beta = 0,
  mode ="sequence"
)
# Results
k_sequences_standard_1_0_df <- k_sequences_standard_1_0$df_results

# plot
plot_sequences_standard_1_0 <- plot_k2(k_sequences_standard_1_0)

# alpha = 0.4 and beta = 0.6
k_sequences_standard_04_06 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.4,
  beta = 0.6,
  mode ="sequence"
)
# Results
k_sequences_standard_04_06_df <- k_sequences_standard_04_06$df_results

# plot
plot_sequences_standard_04_06 <- plot_k2(k_sequences_standard_04_06)

# alpha = 0.3 and beta = 0.7
k_sequences_standard_03_07 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.3,
  beta = 0.7,
  mode ="sequence"
)
# Results
k_sequences_standard_03_07_df <- k_sequences_standard_03_07$df_results

# plot
plot_sequences_standard_03_07 <- plot_k2(k_sequences_standard_03_07)

# alpha = 0.2 and beta = 0.8
k_sequences_standard_02_08 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.2,
  beta = 0.8,
  mode ="sequence"
)
# Results
k_sequences_standard_02_08_df <- k_sequences_standard_02_08$df_results

# plot
plot_sequences_standard_02_08 <- plot_k2(k_sequences_standard_02_08)

# alpha = 0.1 and beta = 0.9
k_sequences_standard_01_09 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.1,
  beta = 0.9,
  mode ="sequence"
)
# Results
k_sequences_standard_01_09_df <- k_sequences_standard_01_09$df_results

# plot
plot_sequences_standard_01_09 <- plot_k2(k_sequences_standard_01_09)

# alpha = 0 and beta = 1
k_sequences_standard_0_1 <- k_validation_pairwaise(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0,
  beta = 1,
  mode ="sequence"
)
# Results
k_sequences_standard_0_1_df <- k_sequences_standard_0_1$df_results

# plot
plot_sequences_standard_0_1 <- plot_k2(k_sequences_standard_0_1)
```

```{r grid search standard}
# APPROACH TAXA
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_stand_taxa_df <- results

#APPROACH sequences
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_stand_seq_df <- results

```

```{r grid search standard beta 0.9}
# APPROACH TAXA
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_stand_taxa_09_df <- results

#APPROACH sequences
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_stand_seq_09_df <- results

```

```{r filter 2(0.00007) pairwaise}
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_especies_filter2_05_05 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.5,
  beta = 0.5,
  mode ="taxonomy"
)
# Results
k_especies_filter2_05_05_df <- k_especies_filter2_05_05$df_results

# plot
plot_especies_filter2_05_05 <- plot_k2(k_especies_filter2_05_05)

# alpha = 0.6 and beta = 0.4
k_especies_filter2_06_04 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.6,
  beta = 0.4,
  mode ="taxonomy"
)
# Results
k_especies_filter2_06_04_df <- k_especies_filter2_06_04$df_results

# plot
plot_especies_filter2_06_04 <- plot_k2(k_especies_filter2_06_04)

# alpha = 0.7 and beta = 0.3
k_especies_filter2_07_03 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.7,
  beta = 0.3,
  mode ="taxonomy"
)
# Results
k_especies_filter2_07_03_df <- k_especies_filter2_07_03$df_results

# plot
plot_especies_filter2_07_03 <- plot_k2(k_especies_filter2_07_03)

# alpha = 0.8 and beta = 0.2
k_especies_filter2_08_02 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.8,
  beta = 0.2,
  mode ="taxonomy"
)
# Results
k_especies_filter2_08_02_df <- k_especies_filter2_08_02$df_results

# plot
plot_especies_filter2_08_02 <- plot_k2(k_especies_filter2_08_02)

# alpha = 0.9 and beta = 0.1
k_especies_filter2_09_01 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.9,
  beta = 0.1,
  mode ="taxonomy"
)
# Results
k_especies_filter2_09_01_df <- k_especies_filter2_09_01$df_results

# plot
plot_especies_filter2_09_01 <- plot_k2(k_especies_filter2_09_01)

# alpha = 1 and beta = 0
k_especies_filter2_1_0 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 1,
  beta = 0,
  mode ="taxonomy"
)
# Results
k_especies_filter2_1_0_df <- k_especies_filter2_1_0$df_results

# plot
plot_especies_filter2_1_0 <- plot_k2(k_especies_filter2_1_0)

# alpha = 0.4 and beta = 0.6
k_especies_filter2_04_06 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.4,
  beta = 0.6,
  mode ="taxonomy"
)
# Results
k_especies_filter2_04_06_df <- k_especies_filter2_04_06$df_results

# plot
plot_especies_filter2_04_06 <- plot_k2(k_especies_filter2_04_06)

# alpha = 0.3 and beta = 0.7
k_especies_filter2_03_07 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.3,
  beta = 0.7,
  mode ="taxonomy"
)
# Results
k_especies_filter2_03_07_df <- k_especies_filter2_03_07$df_results

# plot
plot_especies_filter2_03_07 <- plot_k2(k_especies_filter2_03_07)

# alpha = 0.2 and beta = 0.8
k_especies_filter2_02_08 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.2,
  beta = 0.8,
  mode ="taxonomy"
)
# Results
k_especies_filter2_02_08_df <- k_especies_filter2_02_08$df_results

# plot
plot_especies_filter2_02_08 <- plot_k2(k_especies_filter2_02_08)

# alpha = 0.1 and beta = 0.9
k_especies_filter2_01_09 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.1,
  beta = 0.9,
  mode ="taxonomy"
)
# Results
k_especies_filter2_01_09_df <- k_especies_filter2_01_09$df_results

# plot
plot_especies_filter2_01_09 <- plot_k2(k_especies_filter2_01_09)

# alpha = 0 and beta = 1
k_especies_filter2_0_1 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0,
  beta = 1,
  mode ="taxonomy"
)
# Results
k_especies_filter2_0_1_df <- k_especies_filter2_0_1$df_results

# plot
plot_especies_filter2_0_1 <- plot_k2(k_especies_filter2_0_1)


#SEQUENCES APPROACH
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_sequences_filter2_05_05 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.5,
  beta = 0.5,
  mode ="sequence"
)
# Results
k_sequences_filter2_05_05_df <- k_sequences_filter2_05_05$df_results

# plot
plot_sequences_filter2_05_05 <- plot_k2(k_sequences_filter2_05_05)

# alpha = 0.6 and beta = 0.4
k_sequences_filter2_06_04 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.6,
  beta = 0.4,
  mode ="sequence"
)
# Results
k_sequences_filter2_06_04_df <- k_sequences_filter2_06_04$df_results

# plot
plot_sequences_filter2_06_04 <- plot_k2(k_sequences_filter2_06_04)

# alpha = 0.7 and beta = 0.3
k_sequences_filter2_07_03 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.7,
  beta = 0.3,
  mode ="sequence"
)
# Results
k_sequences_filter2_07_03_df <- k_sequences_filter2_07_03$df_results

# plot
plot_sequences_filter2_07_03 <- plot_k2(k_sequences_filter2_07_03)

# alpha = 0.8 and beta = 0.2
k_sequences_filter2_08_02 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.8,
  beta = 0.2,
  mode ="sequence"
)
# Results
k_sequences_filter2_08_02_df <- k_sequences_filter2_08_02$df_results

# plot
plot_sequences_filter2_08_02 <- plot_k2(k_sequences_filter2_08_02)

# alpha = 0.9 and beta = 0.1
k_sequences_filter2_09_01 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.9,
  beta = 0.1,
  mode ="sequence"
)
# Results
k_sequences_filter2_09_01_df <- k_sequences_filter2_09_01$df_results

# plot
plot_sequences_filter2_09_01 <- plot_k2(k_sequences_filter2_09_01)

# alpha = 1 and beta = 0
k_sequences_filter2_1_0 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 1,
  beta = 0,
  mode ="sequence"
)
# Results
k_sequences_filter2_1_0_df <- k_sequences_filter2_1_0$df_results

# plot
plot_sequences_filter2_1_0 <- plot_k2(k_sequences_filter2_1_0)

# alpha = 0.4 and beta = 0.6
k_sequences_filter2_04_06 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.4,
  beta = 0.6,
  mode ="sequence"
)
# Results
k_sequences_filter2_04_06_df <- k_sequences_filter2_04_06$df_results

# plot
plot_sequences_filter2_04_06 <- plot_k2(k_sequences_filter2_04_06)

# alpha = 0.3 and beta = 0.7
k_sequences_filter2_03_07 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.3,
  beta = 0.7,
  mode ="sequence"
)
# Results
k_sequences_filter2_03_07_df <- k_sequences_filter2_03_07$df_results

# plot
plot_sequences_filter2_03_07 <- plot_k2(k_sequences_filter2_03_07)

# alpha = 0.2 and beta = 0.8
k_sequences_filter2_02_08 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.2,
  beta = 0.8,
  mode ="sequence"
)
# Results
k_sequences_filter2_02_08_df <- k_sequences_filter2_02_08$df_results

# plot
plot_sequences_filter2_02_08 <- plot_k2(k_sequences_filter2_02_08)

# alpha = 0.1 and beta = 0.9
k_sequences_filter2_01_09 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.1,
  beta = 0.9,
  mode ="sequence"
)
# Results
k_sequences_filter2_01_09_df <- k_sequences_filter2_01_09$df_results

# plot
plot_sequences_filter2_01_09 <- plot_k2(k_sequences_filter2_01_09)

# alpha = 0 and beta = 1
k_sequences_filter2_0_1 <- k_validation_pairwaise2(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0,
  beta = 1,
  mode ="sequence"
)
# Results
k_sequences_filter2_0_1_df <- k_sequences_filter2_0_1$df_results

# plot
plot_sequences_filter2_0_1 <- plot_k2(k_sequences_filter2_0_1)
```

```{r grid search filter 2(0.0005)}
# APPROACH TAXA
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise2(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter2_taxa_df <- results

#APPROACH sequences
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise2(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter2_seq_df <- results
```

```{r grid search filter 2 beta 0.9}
# APPROACH TAXA
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise2(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter2_taxa_09_df <- results

#APPROACH sequences
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise2(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter2_seq_09_df <- results

```

```{r filter 3(0.0001) pairwaise}
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_especies_filter3_05_05 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.5,
  beta = 0.5,
  mode ="taxonomy"
)
# Results
k_especies_filter3_05_05_df <- k_especies_filter3_05_05$df_results

# plot
plot_especies_filter3_05_05 <- plot_k2(k_especies_filter3_05_05)

# alpha = 0.6 and beta = 0.4
k_especies_filter3_06_04 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.6,
  beta = 0.4,
  mode ="taxonomy"
)
# Results
k_especies_filter3_06_04_df <- k_especies_filter3_06_04$df_results

# plot
plot_especies_filter3_06_04 <- plot_k2(k_especies_filter3_06_04)

# alpha = 0.7 and beta = 0.3
k_especies_filter3_07_03 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.7,
  beta = 0.3,
  mode ="taxonomy"
)
# Results
k_especies_filter3_07_03_df <- k_especies_filter3_07_03$df_results

# plot
plot_especies_filter3_07_03 <- plot_k2(k_especies_filter3_07_03)

# alpha = 0.8 and beta = 0.2
k_especies_filter3_08_02 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.8,
  beta = 0.2,
  mode ="taxonomy"
)
# Results
k_especies_filter3_08_02_df <- k_especies_filter3_08_02$df_results

# plot
plot_especies_filter3_08_02 <- plot_k2(k_especies_filter3_08_02)

# alpha = 0.9 and beta = 0.1
k_especies_filter3_09_01 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.9,
  beta = 0.1,
  mode ="taxonomy"
)
# Results
k_especies_filter3_09_01_df <- k_especies_filter3_09_01$df_results

# plot
plot_especies_filter3_09_01 <- plot_k2(k_especies_filter3_09_01)

# alpha = 1 and beta = 0
k_especies_filter3_1_0 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 1,
  beta = 0,
  mode ="taxonomy"
)
# Results
k_especies_filter3_1_0_df <- k_especies_filter3_1_0$df_results

# plot
plot_especies_filter3_1_0 <- plot_k2(k_especies_filter3_1_0)

# alpha = 0.4 and beta = 0.6
k_especies_filter3_04_06 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.4,
  beta = 0.6,
  mode ="taxonomy"
)
# Results
k_especies_filter3_04_06_df <- k_especies_filter3_04_06$df_results

# plot
plot_especies_filter3_04_06 <- plot_k2(k_especies_filter3_04_06)

# alpha = 0.3 and beta = 0.7
k_especies_filter3_03_07 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.3,
  beta = 0.7,
  mode ="taxonomy"
)
# Results
k_especies_filter3_03_07_df <- k_especies_filter3_03_07$df_results

# plot
plot_especies_filter3_03_07 <- plot_k2(k_especies_filter3_03_07)

# alpha = 0.2 and beta = 0.8
k_especies_filter3_02_08 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.2,
  beta = 0.8,
  mode ="taxonomy"
)
# Results
k_especies_filter3_02_08_df <- k_especies_filter3_02_08$df_results

# plot
plot_especies_filter3_02_08 <- plot_k2(k_especies_filter3_02_08)

# alpha = 0.1 and beta = 0.9
k_especies_filter3_01_09 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.1,
  beta = 0.9,
  mode ="taxonomy"
)
# Results
k_especies_filter3_01_09_df <- k_especies_filter3_01_09$df_results

# plot
plot_especies_filter3_01_09 <- plot_k2(k_especies_filter3_01_09)

# alpha = 0 and beta = 1
k_especies_filter3_0_1 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0,
  beta = 1,
  mode ="taxonomy"
)
# Results
k_especies_filter3_0_1_df <- k_especies_filter3_0_1$df_results

# plot
plot_especies_filter3_0_1 <- plot_k2(k_especies_filter3_0_1)


#SEQUENCES APPROACH
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_sequences_filter3_05_05 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.5,
  beta = 0.5,
  mode ="sequence"
)
# Results
k_sequences_filter3_05_05_df <- k_sequences_filter3_05_05$df_results

# plot
plot_sequences_filter3_05_05 <- plot_k2(k_sequences_filter3_05_05)

# alpha = 0.6 and beta = 0.4
k_sequences_filter3_06_04 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.6,
  beta = 0.4,
  mode ="sequence"
)
# Results
k_sequences_filter3_06_04_df <- k_sequences_filter3_06_04$df_results

# plot
plot_sequences_filter3_06_04 <- plot_k2(k_sequences_filter3_06_04)

# alpha = 0.7 and beta = 0.3
k_sequences_filter3_07_03 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.7,
  beta = 0.3,
  mode ="sequence"
)
# Results
k_sequences_filter3_07_03_df <- k_sequences_filter3_07_03$df_results

# plot
plot_sequences_filter3_07_03 <- plot_k2(k_sequences_filter3_07_03)

# alpha = 0.8 and beta = 0.2
k_sequences_filter3_08_02 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.8,
  beta = 0.2,
  mode ="sequence"
)
# Results
k_sequences_filter3_08_02_df <- k_sequences_filter3_08_02$df_results

# plot
plot_sequences_filter3_08_02 <- plot_k2(k_sequences_filter3_08_02)

# alpha = 0.9 and beta = 0.1
k_sequences_filter3_09_01 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.9,
  beta = 0.1,
  mode ="sequence"
)
# Results
k_sequences_filter3_09_01_df <- k_sequences_filter3_09_01$df_results

# plot
plot_sequences_filter3_09_01 <- plot_k2(k_sequences_filter3_09_01)

# alpha = 1 and beta = 0
k_sequences_filter3_1_0 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 1,
  beta = 0,
  mode ="sequence"
)
# Results
k_sequences_filter3_1_0_df <- k_sequences_filter3_1_0$df_results

# plot
plot_sequences_filter3_1_0 <- plot_k2(k_sequences_filter3_1_0)

# alpha = 0.4 and beta = 0.6
k_sequences_filter3_04_06 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.4,
  beta = 0.6,
  mode ="sequence"
)
# Results
k_sequences_filter3_04_06_df <- k_sequences_filter3_04_06$df_results

# plot
plot_sequences_filter3_04_06 <- plot_k2(k_sequences_filter3_04_06)

# alpha = 0.3 and beta = 0.7
k_sequences_filter3_03_07 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.3,
  beta = 0.7,
  mode ="sequence"
)
# Results
k_sequences_filter3_03_07_df <- k_sequences_filter3_03_07$df_results

# plot
plot_sequences_filter3_03_07 <- plot_k2(k_sequences_filter3_03_07)

# alpha = 0.2 and beta = 0.8
k_sequences_filter3_02_08 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.2,
  beta = 0.8,
  mode ="sequence"
)
# Results
k_sequences_filter3_02_08_df <- k_sequences_filter3_02_08$df_results

# plot
plot_sequences_filter3_02_08 <- plot_k2(k_sequences_filter3_02_08)

# alpha = 0.1 and beta = 0.9
k_sequences_filter3_01_09 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.1,
  beta = 0.9,
  mode ="sequence"
)
# Results
k_sequences_filter3_01_09_df <- k_sequences_filter3_01_09$df_results

# plot
plot_sequences_filter3_01_09 <- plot_k2(k_sequences_filter3_01_09)

# alpha = 0 and beta = 1
k_sequences_filter3_0_1 <- k_validation_pairwaise3(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0,
  beta = 1,
  mode ="sequence"
)
# Results
k_sequences_filter3_0_1_df <- k_sequences_filter3_0_1$df_results

# plot
plot_sequences_filter3_0_1 <- plot_k2(k_sequences_filter3_0_1)
```

```{r grid search filter 3(0.0010)}
# APPROACH TAXA
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise3(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter3_taxa_df <- results

#APPROACH sequences
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise3(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter3_seq_df <- results
```

```{r grid search filter 3 beta 0.9}
# APPROACH TAXA
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise3(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter3_taxa_09_df <- results

#APPROACH sequences
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise3(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter3_seq_09_df <- results

```

```{r filter 4(0.0002) pairwaise}
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_especies_filter4_05_05 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.5,
  beta = 0.5,
  mode ="taxonomy"
)
# Results
k_especies_filter4_05_05_df <- k_especies_filter4_05_05$df_results

# plot
plot_especies_filter4_05_05 <- plot_k2(k_especies_filter4_05_05)

# alpha = 0.6 and beta = 0.4
k_especies_filter4_06_04 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.6,
  beta = 0.4,
  mode ="taxonomy"
)
# Results
k_especies_filter4_06_04_df <- k_especies_filter4_06_04$df_results

# plot
plot_especies_filter4_06_04 <- plot_k2(k_especies_filter4_06_04)

# alpha = 0.7 and beta = 0.3
k_especies_filter4_07_03 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.7,
  beta = 0.3,
  mode ="taxonomy"
)
# Results
k_especies_filter4_07_03_df <- k_especies_filter4_07_03$df_results

# plot
plot_especies_filter4_07_03 <- plot_k2(k_especies_filter4_07_03)

# alpha = 0.8 and beta = 0.2
k_especies_filter4_08_02 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.8,
  beta = 0.2,
  mode ="taxonomy"
)
# Results
k_especies_filter4_08_02_df <- k_especies_filter4_08_02$df_results

# plot
plot_especies_filter4_08_02 <- plot_k2(k_especies_filter4_08_02)

# alpha = 0.9 and beta = 0.1
k_especies_filter4_09_01 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.9,
  beta = 0.1,
  mode ="taxonomy"
)
# Results
k_especies_filter4_09_01_df <- k_especies_filter4_09_01$df_results

# plot
plot_especies_filter4_09_01 <- plot_k2(k_especies_filter4_09_01)

# alpha = 1 and beta = 0
k_especies_filter4_1_0 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 1,
  beta = 0,
  mode ="taxonomy"
)
# Results
k_especies_filter4_1_0_df <- k_especies_filter4_1_0$df_results

# plot
plot_especies_filter4_1_0 <- plot_k2(k_especies_filter4_1_0)

# alpha = 0.4 and beta = 0.6
k_especies_filter4_04_06 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.4,
  beta = 0.6,
  mode ="taxonomy"
)
# Results
k_especies_filter4_04_06_df <- k_especies_filter4_04_06$df_results

# plot
plot_especies_filter4_04_06 <- plot_k2(k_especies_filter4_04_06)

# alpha = 0.3 and beta = 0.7
k_especies_filter4_03_07 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.3,
  beta = 0.7,
  mode ="taxonomy"
)
# Results
k_especies_filter4_03_07_df <- k_especies_filter4_03_07$df_results

# plot
plot_especies_filter4_03_07 <- plot_k2(k_especies_filter4_03_07)

# alpha = 0.2 and beta = 0.8
k_especies_filter4_02_08 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.2,
  beta = 0.8,
  mode ="taxonomy"
)
# Results
k_especies_filter4_02_08_df <- k_especies_filter4_02_08$df_results

# plot
plot_especies_filter4_02_08 <- plot_k2(k_especies_filter4_02_08)

# alpha = 0.1 and beta = 0.9
k_especies_filter4_01_09 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.1,
  beta = 0.9,
  mode ="taxonomy"
)
# Results
k_especies_filter4_01_09_df <- k_especies_filter4_01_09$df_results

# plot
plot_especies_filter4_01_09 <- plot_k2(k_especies_filter4_01_09)

# alpha = 0 and beta = 1
k_especies_filter4_0_1 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0,
  beta = 1,
  mode ="taxonomy"
)
# Results
k_especies_filter4_0_1_df <- k_especies_filter4_0_1$df_results

# plot
plot_especies_filter4_0_1 <- plot_k2(k_especies_filter4_0_1)


#SEQUENCES APPROACH
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_sequences_filter4_05_05 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.5,
  beta = 0.5,
  mode ="sequence"
)
# Results
k_sequences_filter4_05_05_df <- k_sequences_filter4_05_05$df_results

# plot
plot_sequences_filter4_05_05 <- plot_k2(k_sequences_filter4_05_05)

# alpha = 0.6 and beta = 0.4
k_sequences_filter4_06_04 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.6,
  beta = 0.4,
  mode ="sequence"
)
# Results
k_sequences_filter4_06_04_df <- k_sequences_filter4_06_04$df_results

# plot
plot_sequences_filter4_06_04 <- plot_k2(k_sequences_filter4_06_04)

# alpha = 0.7 and beta = 0.3
k_sequences_filter4_07_03 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.7,
  beta = 0.3,
  mode ="sequence"
)
# Results
k_sequences_filter4_07_03_df <- k_sequences_filter4_07_03$df_results

# plot
plot_sequences_filter4_07_03 <- plot_k2(k_sequences_filter4_07_03)

# alpha = 0.8 and beta = 0.2
k_sequences_filter4_08_02 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.8,
  beta = 0.2,
  mode ="sequence"
)
# Results
k_sequences_filter4_08_02_df <- k_sequences_filter4_08_02$df_results

# plot
plot_sequences_filter4_08_02 <- plot_k2(k_sequences_filter4_08_02)

# alpha = 0.9 and beta = 0.1
k_sequences_filter4_09_01 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.9,
  beta = 0.1,
  mode ="sequence"
)
# Results
k_sequences_filter4_09_01_df <- k_sequences_filter4_09_01$df_results

# plot
plot_sequences_filter4_09_01 <- plot_k2(k_sequences_filter4_09_01)

# alpha = 1 and beta = 0
k_sequences_filter4_1_0 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 1,
  beta = 0,
  mode ="sequence"
)
# Results
k_sequences_filter4_1_0_df <- k_sequences_filter4_1_0$df_results

# plot
plot_sequences_filter4_1_0 <- plot_k2(k_sequences_filter4_1_0)

# alpha = 0.4 and beta = 0.6
k_sequences_filter4_04_06 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.4,
  beta = 0.6,
  mode ="sequence"
)
# Results
k_sequences_filter4_04_06_df <- k_sequences_filter4_04_06$df_results

# plot
plot_sequences_filter4_04_06 <- plot_k2(k_sequences_filter4_04_06)

# alpha = 0.3 and beta = 0.7
k_sequences_filter4_03_07 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.3,
  beta = 0.7,
  mode ="sequence"
)
# Results
k_sequences_filter4_03_07_df <- k_sequences_filter4_03_07$df_results

# plot
plot_sequences_filter4_03_07 <- plot_k2(k_sequences_filter4_03_07)

# alpha = 0.2 and beta = 0.8
k_sequences_filter4_02_08 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.2,
  beta = 0.8,
  mode ="sequence"
)
# Results
k_sequences_filter4_02_08_df <- k_sequences_filter4_02_08$df_results

# plot
plot_sequences_filter4_02_08 <- plot_k2(k_sequences_filter4_02_08)

# alpha = 0.1 and beta = 0.9
k_sequences_filter4_01_09 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.1,
  beta = 0.9,
  mode ="sequence"
)
# Results
k_sequences_filter4_01_09_df <- k_sequences_filter4_01_09$df_results

# plot
plot_sequences_filter4_01_09 <- plot_k2(k_sequences_filter4_01_09)

# alpha = 0 and beta = 1
k_sequences_filter4_0_1 <- k_validation_pairwaise4(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0,
  beta = 1,
  mode ="sequence"
)
# Results
k_sequences_filter4_0_1_df <- k_sequences_filter4_0_1$df_results

# plot
plot_sequences_filter4_0_1 <- plot_k2(k_sequences_filter4_0_1)
```

```{r grid search filter 4(0.0007)}
# APPROACH TAXA
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise4(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter4_taxa_df <- results

#APPROACH sequences
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise4(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter4_seq_df <- results
```

```{r grid search filter 4 beta 0.9}
# APPROACH TAXA
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise4(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter4_taxa_09_df <- results

#APPROACH sequences
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise4(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter4_seq_09_df <- results

```

```{r filter 5(0.0003) pairwaise}
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_especies_filter5_05_05 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.5,
  beta = 0.5,
  mode ="taxonomy"
)
# Results
k_especies_filter5_05_05_df <- k_especies_filter5_05_05$df_results

# plot
plot_especies_filter5_05_05 <- plot_k2(k_especies_filter5_05_05)

# alpha = 0.6 and beta = 0.4
k_especies_filter5_06_04 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.6,
  beta = 0.4,
  mode ="taxonomy"
)
# Results
k_especies_filter5_06_04_df <- k_especies_filter5_06_04$df_results

# plot
plot_especies_filter5_06_04 <- plot_k2(k_especies_filter5_06_04)

# alpha = 0.7 and beta = 0.3
k_especies_filter5_07_03 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.7,
  beta = 0.3,
  mode ="taxonomy"
)
# Results
k_especies_filter5_07_03_df <- k_especies_filter5_07_03$df_results

# plot
plot_especies_filter5_07_03 <- plot_k2(k_especies_filter5_07_03)

# alpha = 0.8 and beta = 0.2
k_especies_filter5_08_02 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.8,
  beta = 0.2,
  mode ="taxonomy"
)
# Results
k_especies_filter5_08_02_df <- k_especies_filter5_08_02$df_results

# plot
plot_especies_filter5_08_02 <- plot_k2(k_especies_filter5_08_02)

# alpha = 0.9 and beta = 0.1
k_especies_filter5_09_01 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.9,
  beta = 0.1,
  mode ="taxonomy"
)
# Results
k_especies_filter5_09_01_df <- k_especies_filter5_09_01$df_results

# plot
plot_especies_filter5_09_01 <- plot_k2(k_especies_filter5_09_01)

# alpha = 1 and beta = 0
k_especies_filter5_1_0 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 1,
  beta = 0,
  mode ="taxonomy"
)
# Results
k_especies_filter5_1_0_df <- k_especies_filter5_1_0$df_results

# plot
plot_especies_filter5_1_0 <- plot_k2(k_especies_filter5_1_0)

# alpha = 0.4 and beta = 0.6
k_especies_filter5_04_06 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.4,
  beta = 0.6,
  mode ="taxonomy"
)
# Results
k_especies_filter5_04_06_df <- k_especies_filter5_04_06$df_results

# plot
plot_especies_filter5_04_06 <- plot_k2(k_especies_filter5_04_06)

# alpha = 0.3 and beta = 0.7
k_especies_filter5_03_07 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.3,
  beta = 0.7,
  mode ="taxonomy"
)
# Results
k_especies_filter5_03_07_df <- k_especies_filter5_03_07$df_results

# plot
plot_especies_filter5_03_07 <- plot_k2(k_especies_filter5_03_07)

# alpha = 0.2 and beta = 0.8
k_especies_filter5_02_08 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.2,
  beta = 0.8,
  mode ="taxonomy"
)
# Results
k_especies_filter5_02_08_df <- k_especies_filter5_02_08$df_results

# plot
plot_especies_filter5_02_08 <- plot_k2(k_especies_filter5_02_08)

# alpha = 0.1 and beta = 0.9
k_especies_filter5_01_09 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.1,
  beta = 0.9,
  mode ="taxonomy"
)
# Results
k_especies_filter5_01_09_df <- k_especies_filter5_01_09$df_results

# plot
plot_especies_filter5_01_09 <- plot_k2(k_especies_filter5_01_09)

# alpha = 0 and beta = 1
k_especies_filter5_0_1 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0,
  beta = 1,
  mode ="taxonomy"
)
# Results
k_especies_filter5_0_1_df <- k_especies_filter5_0_1$df_results

# plot
plot_especies_filter5_0_1 <- plot_k2(k_especies_filter5_0_1)


#SEQUENCES APPROACH
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_sequences_filter5_05_05 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.5,
  beta = 0.5,
  mode ="sequence"
)
# Results
k_sequences_filter5_05_05_df <- k_sequences_filter5_05_05$df_results

# plot
plot_sequences_filter5_05_05 <- plot_k2(k_sequences_filter5_05_05)

# alpha = 0.6 and beta = 0.4
k_sequences_filter5_06_04 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.6,
  beta = 0.4,
  mode ="sequence"
)
# Results
k_sequences_filter5_06_04_df <- k_sequences_filter5_06_04$df_results

# plot
plot_sequences_filter5_06_04 <- plot_k2(k_sequences_filter5_06_04)

# alpha = 0.7 and beta = 0.3
k_sequences_filter5_07_03 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.7,
  beta = 0.3,
  mode ="sequence"
)
# Results
k_sequences_filter5_07_03_df <- k_sequences_filter5_07_03$df_results

# plot
plot_sequences_filter5_07_03 <- plot_k2(k_sequences_filter5_07_03)

# alpha = 0.8 and beta = 0.2
k_sequences_filter5_08_02 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.8,
  beta = 0.2,
  mode ="sequence"
)
# Results
k_sequences_filter5_08_02_df <- k_sequences_filter5_08_02$df_results

# plot
plot_sequences_filter5_08_02 <- plot_k2(k_sequences_filter5_08_02)

# alpha = 0.9 and beta = 0.1
k_sequences_filter5_09_01 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.9,
  beta = 0.1,
  mode ="sequence"
)
# Results
k_sequences_filter5_09_01_df <- k_sequences_filter5_09_01$df_results

# plot
plot_sequences_filter5_09_01 <- plot_k2(k_sequences_filter5_09_01)

# alpha = 1 and beta = 0
k_sequences_filter5_1_0 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 1,
  beta = 0,
  mode ="sequence"
)
# Results
k_sequences_filter5_1_0_df <- k_sequences_filter5_1_0$df_results

# plot
plot_sequences_filter5_1_0 <- plot_k2(k_sequences_filter5_1_0)

# alpha = 0.4 and beta = 0.6
k_sequences_filter5_04_06 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.4,
  beta = 0.6,
  mode ="sequence"
)
# Results
k_sequences_filter5_04_06_df <- k_sequences_filter5_04_06$df_results

# plot
plot_sequences_filter5_04_06 <- plot_k2(k_sequences_filter5_04_06)

# alpha = 0.3 and beta = 0.7
k_sequences_filter5_03_07 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.3,
  beta = 0.7,
  mode ="sequence"
)
# Results
k_sequences_filter5_03_07_df <- k_sequences_filter5_03_07$df_results

# plot
plot_sequences_filter5_03_07 <- plot_k2(k_sequences_filter5_03_07)

# alpha = 0.2 and beta = 0.8
k_sequences_filter5_02_08 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.2,
  beta = 0.8,
  mode ="sequence"
)
# Results
k_sequences_filter5_02_08_df <- k_sequences_filter5_02_08$df_results

# plot
plot_sequences_filter5_02_08 <- plot_k2(k_sequences_filter5_02_08)

# alpha = 0.1 and beta = 0.9
k_sequences_filter5_01_09 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.1,
  beta = 0.9,
  mode ="sequence"
)
# Results
k_sequences_filter5_01_09_df <- k_sequences_filter5_01_09$df_results

# plot
plot_sequences_filter5_01_09 <- plot_k2(k_sequences_filter5_01_09)

# alpha = 0 and beta = 1
k_sequences_filter5_0_1 <- k_validation_pairwaise5(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0,
  beta = 1,
  mode ="sequence"
)
# Results
k_sequences_filter5_0_1_df <- k_sequences_filter5_0_1$df_results

# plot
plot_sequences_filter5_0_1 <- plot_k2(k_sequences_filter5_0_1)
```

```{r grid search filter 5(0.0003)}
# APPROACH TAXA
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise5(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter5_taxa_df <- results

#APPROACH sequences
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise5(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter5_seq_df <- results
```

```{r grid search filter 5 beta 0.9}
# APPROACH TAXA
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise5(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter5_taxa_09_df <- results

#APPROACH sequences
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise5(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter5_seq_09_df <- results

```

```{r filter 6(0.0004) pairwaise}
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_especies_filter6_05_05 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.5,
  beta = 0.5,
  mode ="taxonomy"
)
# Results
k_especies_filter6_05_05_df <- k_especies_filter6_05_05$df_results

# plot
plot_especies_filter6_05_05 <- plot_k2(k_especies_filter6_05_05)

# alpha = 0.6 and beta = 0.4
k_especies_filter6_06_04 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.6,
  beta = 0.4,
  mode ="taxonomy"
)
# Results
k_especies_filter6_06_04_df <- k_especies_filter6_06_04$df_results

# plot
plot_especies_filter6_06_04 <- plot_k2(k_especies_filter6_06_04)

# alpha = 0.7 and beta = 0.3
k_especies_filter6_07_03 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.7,
  beta = 0.3,
  mode ="taxonomy"
)
# Results
k_especies_filter6_07_03_df <- k_especies_filter6_07_03$df_results

# plot
plot_especies_filter6_07_03 <- plot_k2(k_especies_filter6_07_03)

# alpha = 0.8 and beta = 0.2
k_especies_filter6_08_02 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.8,
  beta = 0.2,
  mode ="taxonomy"
)
# Results
k_especies_filter6_08_02_df <- k_especies_filter6_08_02$df_results

# plot
plot_especies_filter6_08_02 <- plot_k2(k_especies_filter6_08_02)

# alpha = 0.9 and beta = 0.1
k_especies_filter6_09_01 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.9,
  beta = 0.1,
  mode ="taxonomy"
)
# Results
k_especies_filter6_09_01_df <- k_especies_filter6_09_01$df_results

# plot
plot_especies_filter6_09_01 <- plot_k2(k_especies_filter6_09_01)

# alpha = 1 and beta = 0
k_especies_filter6_1_0 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 1,
  beta = 0,
  mode ="taxonomy"
)
# Results
k_especies_filter6_1_0_df <- k_especies_filter6_1_0$df_results

# plot
plot_especies_filter6_1_0 <- plot_k2(k_especies_filter6_1_0)

# alpha = 0.4 and beta = 0.6
k_especies_filter6_04_06 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.4,
  beta = 0.6,
  mode ="taxonomy"
)
# Results
k_especies_filter6_04_06_df <- k_especies_filter6_04_06$df_results

# plot
plot_especies_filter6_04_06 <- plot_k2(k_especies_filter6_04_06)

# alpha = 0.3 and beta = 0.7
k_especies_filter6_03_07 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.3,
  beta = 0.7,
  mode ="taxonomy"
)
# Results
k_especies_filter6_03_07_df <- k_especies_filter6_03_07$df_results

# plot
plot_especies_filter6_03_07 <- plot_k2(k_especies_filter6_03_07)

# alpha = 0.2 and beta = 0.8
k_especies_filter6_02_08 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.2,
  beta = 0.8,
  mode ="taxonomy"
)
# Results
k_especies_filter6_02_08_df <- k_especies_filter6_02_08$df_results

# plot
plot_especies_filter6_02_08 <- plot_k2(k_especies_filter6_02_08)

# alpha = 0.1 and beta = 0.9
k_especies_filter6_01_09 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.1,
  beta = 0.9,
  mode ="taxonomy"
)
# Results
k_especies_filter6_01_09_df <- k_especies_filter6_01_09$df_results

# plot
plot_especies_filter6_01_09 <- plot_k2(k_especies_filter6_01_09)

# alpha = 0 and beta = 1
k_especies_filter6_0_1 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0,
  beta = 1,
  mode ="taxonomy"
)
# Results
k_especies_filter6_0_1_df <- k_especies_filter6_0_1$df_results

# plot
plot_especies_filter6_0_1 <- plot_k2(k_especies_filter6_0_1)


#SEQUENCES APPROACH
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_sequences_filter6_05_05 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.5,
  beta = 0.5,
  mode ="sequence"
)
# Results
k_sequences_filter6_05_05_df <- k_sequences_filter6_05_05$df_results

# plot
plot_sequences_filter6_05_05 <- plot_k2(k_sequences_filter6_05_05)

# alpha = 0.6 and beta = 0.4
k_sequences_filter6_06_04 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.6,
  beta = 0.4,
  mode ="sequence"
)
# Results
k_sequences_filter6_06_04_df <- k_sequences_filter6_06_04$df_results

# plot
plot_sequences_filter6_06_04 <- plot_k2(k_sequences_filter6_06_04)

# alpha = 0.7 and beta = 0.3
k_sequences_filter6_07_03 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.7,
  beta = 0.3,
  mode ="sequence"
)
# Results
k_sequences_filter6_07_03_df <- k_sequences_filter6_07_03$df_results

# plot
plot_sequences_filter6_07_03 <- plot_k2(k_sequences_filter6_07_03)

# alpha = 0.8 and beta = 0.2
k_sequences_filter6_08_02 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.8,
  beta = 0.2,
  mode ="sequence"
)
# Results
k_sequences_filter6_08_02_df <- k_sequences_filter6_08_02$df_results

# plot
plot_sequences_filter6_08_02 <- plot_k2(k_sequences_filter6_08_02)

# alpha = 0.9 and beta = 0.1
k_sequences_filter6_09_01 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.9,
  beta = 0.1,
  mode ="sequence"
)
# Results
k_sequences_filter6_09_01_df <- k_sequences_filter6_09_01$df_results

# plot
plot_sequences_filter6_09_01 <- plot_k2(k_sequences_filter6_09_01)

# alpha = 1 and beta = 0
k_sequences_filter6_1_0 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 1,
  beta = 0,
  mode ="sequence"
)
# Results
k_sequences_filter6_1_0_df <- k_sequences_filter6_1_0$df_results

# plot
plot_sequences_filter6_1_0 <- plot_k2(k_sequences_filter6_1_0)

# alpha = 0.4 and beta = 0.6
k_sequences_filter6_04_06 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.4,
  beta = 0.6,
  mode ="sequence"
)
# Results
k_sequences_filter6_04_06_df <- k_sequences_filter6_04_06$df_results

# plot
plot_sequences_filter6_04_06 <- plot_k2(k_sequences_filter6_04_06)

# alpha = 0.3 and beta = 0.7
k_sequences_filter6_03_07 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.3,
  beta = 0.7,
  mode ="sequence"
)
# Results
k_sequences_filter6_03_07_df <- k_sequences_filter6_03_07$df_results

# plot
plot_sequences_filter6_03_07 <- plot_k2(k_sequences_filter6_03_07)

# alpha = 0.2 and beta = 0.8
k_sequences_filter6_02_08 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.2,
  beta = 0.8,
  mode ="sequence"
)
# Results
k_sequences_filter6_02_08_df <- k_sequences_filter6_02_08$df_results

# plot
plot_sequences_filter6_02_08 <- plot_k2(k_sequences_filter6_02_08)

# alpha = 0.1 and beta = 0.9
k_sequences_filter6_01_09 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.1,
  beta = 0.9,
  mode ="sequence"
)
# Results
k_sequences_filter6_01_09_df <- k_sequences_filter6_01_09$df_results

# plot
plot_sequences_filter6_01_09 <- plot_k2(k_sequences_filter6_01_09)

# alpha = 0 and beta = 1
k_sequences_filter6_0_1 <- k_validation_pairwaise6(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0,
  beta = 1,
  mode ="sequence"
)
# Results
k_sequences_filter6_0_1_df <- k_sequences_filter6_0_1$df_results

# plot
plot_sequences_filter6_0_1 <- plot_k2(k_sequences_filter6_0_1)
```

```{r grid search filter 6(0.0009)}
# APPROACH TAXA
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise6(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter6_taxa_df <- results

#APPROACH sequences
alpha_vals <- seq(0, 1 , 0.1) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise6(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter6_seq_df <- results
```

```{r grid search filter 6 beta 0.9}
# APPROACH TAXA
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise6(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_taxa,  
    alpha = alpha,
    beta = beta,
    mode = "taxonomy" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter6_taxa_09_df <- results

#APPROACH sequences
alpha_vals <- seq(0.01, 0.09 , by = 0.01) 
results <- data.frame()

for (alpha in alpha_vals) {
  beta <- 1 - alpha
  cat("Runnning alpha =", alpha, "beta =", beta, "\n")
  
  k_fit <- k_validation_pairwaise6(
    OTU_table = OTU_table_filt_df,
    ground_truth = ground_truth_sequences,  
    alpha = alpha,
    beta = beta,
    mode = "sequence" 
  )
  
  # Extract global metrics
  metrics <- k_fit$global_metrics
  filtered <- k_fit$filtered_values
  unfiltered <- k_fit$unfiltered_values
  
  metrics_1 <- metrics[metrics$criterion == "k >= k_0", ]
  
  metrics_2 <- metrics[metrics$criterion == "k >= sig_upper", ]
  
  metrics_3 <- metrics[metrics$criterion == "k >= sig_lower", ]
  
  results <- rbind(results, data.frame(
    alpha = alpha,
    beta = beta,
    Recovered_ASVs1 = length(k_fit$recovered_asv_ap1),
    Recovered_ASVs2 = length(k_fit$recovered_asv_ap2),
    Recovered_ASVs3 = length(k_fit$recovered_asv_ap3),
    precision1 = metrics_1$precision,
    precision2 = metrics_2$precision,
    precision3 = metrics_3$precision,
    #recall1 = metrics$recall,
    #recall2 = metrics_2$recall,
    #FDR1 = metrics_1$FDR
    #FDR2 = metrics_2$FDR,,
    #F11 = metrics_1$F1,
    #F12 = metrics_2$F1,
    k_inicial = filtered$k,
    k_max = k_fit$k_max
    #time = as.numeric(k_fit$time))
  ))
}

# Display results
grid_search_filter6_seq_09_df <- results

```

```{r filter7(0.00035)}
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_especies_filter7_05_05 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.5,
  beta = 0.5,
  mode ="taxonomy"
)
# Results
k_especies_filter7_05_05_df <- k_especies_filter7_05_05$df_results

# plot
plot_especies_filter7_05_05 <- plot_k2(k_especies_filter7_05_05)

# alpha = 0.6 and beta = 0.4
k_especies_filter7_06_04 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.6,
  beta = 0.4,
  mode ="taxonomy"
)
# Results
k_especies_filter7_06_04_df <- k_especies_filter7_06_04$df_results

# plot
plot_especies_filter7_06_04 <- plot_k2(k_especies_filter7_06_04)

# alpha = 0.7 and beta = 0.3
k_especies_filter7_07_03 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.7,
  beta = 0.3,
  mode ="taxonomy"
)
# Results
k_especies_filter7_07_03_df <- k_especies_filter7_07_03$df_results

# plot
plot_especies_filter7_07_03 <- plot_k2(k_especies_filter7_07_03)

# alpha = 0.8 and beta = 0.2
k_especies_filter7_08_02 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.8,
  beta = 0.2,
  mode ="taxonomy"
)
# Results
k_especies_filter7_08_02_df <- k_especies_filter7_08_02$df_results

# plot
plot_especies_filter7_08_02 <- plot_k2(k_especies_filter7_08_02)

# alpha = 0.9 and beta = 0.1
k_especies_filter7_09_01 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.9,
  beta = 0.1,
  mode ="taxonomy"
)
# Results
k_especies_filter7_09_01_df <- k_especies_filter7_09_01$df_results

# plot
plot_especies_filter7_09_01 <- plot_k2(k_especies_filter7_09_01)

# alpha = 1 and beta = 0
k_especies_filter7_1_0 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 1,
  beta = 0,
  mode ="taxonomy"
)
# Results
k_especies_filter7_1_0_df <- k_especies_filter7_1_0$df_results

# plot
plot_especies_filter7_1_0 <- plot_k2(k_especies_filter7_1_0)

# alpha = 0.4 and beta = 0.6
k_especies_filter7_04_06 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.4,
  beta = 0.6,
  mode ="taxonomy"
)
# Results
k_especies_filter7_04_06_df <- k_especies_filter7_04_06$df_results

# plot
plot_especies_filter7_04_06 <- plot_k2(k_especies_filter7_04_06)

# alpha = 0.3 and beta = 0.7
k_especies_filter7_03_07 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.3,
  beta = 0.7,
  mode ="taxonomy"
)
# Results
k_especies_filter7_03_07_df <- k_especies_filter7_03_07$df_results

# plot
plot_especies_filter7_03_07 <- plot_k2(k_especies_filter7_03_07)

# alpha = 0.2 and beta = 0.8
k_especies_filter7_02_08 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.2,
  beta = 0.8,
  mode ="taxonomy"
)
# Results
k_especies_filter7_02_08_df <- k_especies_filter7_02_08$df_results

# plot
plot_especies_filter7_02_08 <- plot_k2(k_especies_filter7_02_08)

# alpha = 0.1 and beta = 0.9
k_especies_filter7_01_09 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.1,
  beta = 0.9,
  mode ="taxonomy"
)
# Results
k_especies_filter7_01_09_df <- k_especies_filter7_01_09$df_results

# plot
plot_especies_filter7_01_09 <- plot_k2(k_especies_filter7_01_09)

# alpha = 0 and beta = 1
k_especies_filter7_0_1 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0,
  beta = 1,
  mode ="taxonomy"
)
# Results
k_especies_filter7_0_1_df <- k_especies_filter7_0_1$df_results

# plot
plot_especies_filter7_0_1 <- plot_k2(k_especies_filter7_0_1)


#SEQUENCES APPROACH
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_sequences_filter7_05_05 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.5,
  beta = 0.5,
  mode ="sequence"
)
# Results
k_sequences_filter7_05_05_df <- k_sequences_filter7_05_05$df_results

# plot
plot_sequences_filter7_05_05 <- plot_k2(k_sequences_filter7_05_05)

# alpha = 0.6 and beta = 0.4
k_sequences_filter7_06_04 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.6,
  beta = 0.4,
  mode ="sequence"
)
# Results
k_sequences_filter7_06_04_df <- k_sequences_filter7_06_04$df_results

# plot
plot_sequences_filter7_06_04 <- plot_k2(k_sequences_filter7_06_04)

# alpha = 0.7 and beta = 0.3
k_sequences_filter7_07_03 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.7,
  beta = 0.3,
  mode ="sequence"
)
# Results
k_sequences_filter7_07_03_df <- k_sequences_filter7_07_03$df_results

# plot
plot_sequences_filter7_07_03 <- plot_k2(k_sequences_filter7_07_03)

# alpha = 0.8 and beta = 0.2
k_sequences_filter7_08_02 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.8,
  beta = 0.2,
  mode ="sequence"
)
# Results
k_sequences_filter7_08_02_df <- k_sequences_filter7_08_02$df_results

# plot
plot_sequences_filter7_08_02 <- plot_k2(k_sequences_filter7_08_02)

# alpha = 0.9 and beta = 0.1
k_sequences_filter7_09_01 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.9,
  beta = 0.1,
  mode ="sequence"
)
# Results
k_sequences_filter7_09_01_df <- k_sequences_filter7_09_01$df_results

# plot
plot_sequences_filter7_09_01 <- plot_k2(k_sequences_filter7_09_01)

# alpha = 1 and beta = 0
k_sequences_filter7_1_0 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 1,
  beta = 0,
  mode ="sequence"
)
# Results
k_sequences_filter7_1_0_df <- k_sequences_filter7_1_0$df_results

# plot
plot_sequences_filter7_1_0 <- plot_k2(k_sequences_filter7_1_0)

# alpha = 0.4 and beta = 0.6
k_sequences_filter7_04_06 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.4,
  beta = 0.6,
  mode ="sequence"
)
# Results
k_sequences_filter7_04_06_df <- k_sequences_filter7_04_06$df_results

# plot
plot_sequences_filter7_04_06 <- plot_k2(k_sequences_filter7_04_06)

# alpha = 0.3 and beta = 0.7
k_sequences_filter7_03_07 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.3,
  beta = 0.7,
  mode ="sequence"
)
# Results
k_sequences_filter7_03_07_df <- k_sequences_filter7_03_07$df_results

# plot
plot_sequences_filter7_03_07 <- plot_k2(k_sequences_filter7_03_07)

# alpha = 0.2 and beta = 0.8
k_sequences_filter7_02_08 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.2,
  beta = 0.8,
  mode ="sequence"
)
# Results
k_sequences_filter7_02_08_df <- k_sequences_filter7_02_08$df_results

# plot
plot_sequences_filter7_02_08 <- plot_k2(k_sequences_filter7_02_08)

# alpha = 0.1 and beta = 0.9
k_sequences_filter7_01_09 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.1,
  beta = 0.9,
  mode ="sequence"
)
# Results
k_sequences_filter7_01_09_df <- k_sequences_filter7_01_09$df_results

# plot
plot_sequences_filter7_01_09 <- plot_k2(k_sequences_filter7_01_09)

# alpha = 0 and beta = 1
k_sequences_filter7_0_1 <- k_validation_pairwaise7(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0,
  beta = 1,
  mode ="sequence"
)
# Results
k_sequences_filter7_0_1_df <- k_sequences_filter7_0_1$df_results

# plot
plot_sequences_filter7_0_1 <- plot_k2(k_sequences_filter7_0_1)
```

```{r filter8(0.00042)}
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_especies_filter8_05_05 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.5,
  beta = 0.5,
  mode ="taxonomy"
)
# Results
k_especies_filter8_05_05_df <- k_especies_filter8_05_05$df_results

# plot
plot_especies_filter8_05_05 <- plot_k2(k_especies_filter8_05_05)

# alpha = 0.6 and beta = 0.4
k_especies_filter8_06_04 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.6,
  beta = 0.4,
  mode ="taxonomy"
)
# Results
k_especies_filter8_06_04_df <- k_especies_filter8_06_04$df_results

# plot
plot_especies_filter8_06_04 <- plot_k2(k_especies_filter8_06_04)

# alpha = 0.7 and beta = 0.3
k_especies_filter8_07_03 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.7,
  beta = 0.3,
  mode ="taxonomy"
)
# Results
k_especies_filter8_07_03_df <- k_especies_filter8_07_03$df_results

# plot
plot_especies_filter8_07_03 <- plot_k2(k_especies_filter8_07_03)

# alpha = 0.8 and beta = 0.2
k_especies_filter8_08_02 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.8,
  beta = 0.2,
  mode ="taxonomy"
)
# Results
k_especies_filter8_08_02_df <- k_especies_filter8_08_02$df_results

# plot
plot_especies_filter8_08_02 <- plot_k2(k_especies_filter8_08_02)

# alpha = 0.9 and beta = 0.1
k_especies_filter8_09_01 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.9,
  beta = 0.1,
  mode ="taxonomy"
)
# Results
k_especies_filter8_09_01_df <- k_especies_filter8_09_01$df_results

# plot
plot_especies_filter8_09_01 <- plot_k2(k_especies_filter8_09_01)

# alpha = 1 and beta = 0
k_especies_filter8_1_0 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 1,
  beta = 0,
  mode ="taxonomy"
)
# Results
k_especies_filter8_1_0_df <- k_especies_filter8_1_0$df_results

# plot
plot_especies_filter8_1_0 <- plot_k2(k_especies_filter8_1_0)

# alpha = 0.4 and beta = 0.6
k_especies_filter8_04_06 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.4,
  beta = 0.6,
  mode ="taxonomy"
)
# Results
k_especies_filter8_04_06_df <- k_especies_filter8_04_06$df_results

# plot
plot_especies_filter8_04_06 <- plot_k2(k_especies_filter8_04_06)

# alpha = 0.3 and beta = 0.7
k_especies_filter8_03_07 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.3,
  beta = 0.7,
  mode ="taxonomy"
)
# Results
k_especies_filter8_03_07_df <- k_especies_filter8_03_07$df_results

# plot
plot_especies_filter8_03_07 <- plot_k2(k_especies_filter8_03_07)

# alpha = 0.2 and beta = 0.8
k_especies_filter8_02_08 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.2,
  beta = 0.8,
  mode ="taxonomy"
)
# Results
k_especies_filter8_02_08_df <- k_especies_filter8_02_08$df_results

# plot
plot_especies_filter8_02_08 <- plot_k2(k_especies_filter8_02_08)

# alpha = 0.1 and beta = 0.9
k_especies_filter8_01_09 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.1,
  beta = 0.9,
  mode ="taxonomy"
)
# Results
k_especies_filter8_01_09_df <- k_especies_filter8_01_09$df_results

# plot
plot_especies_filter8_01_09 <- plot_k2(k_especies_filter8_01_09)

# alpha = 0 and beta = 1
k_especies_filter8_0_1 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0,
  beta = 1,
  mode ="taxonomy"
)
# Results
k_especies_filter8_0_1_df <- k_especies_filter8_0_1$df_results

# plot
plot_especies_filter8_0_1 <- plot_k2(k_especies_filter8_0_1)


#SEQUENCES APPROACH
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_sequences_filter8_05_05 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.5,
  beta = 0.5,
  mode ="sequence"
)
# Results
k_sequences_filter8_05_05_df <- k_sequences_filter8_05_05$df_results

# plot
plot_sequences_filter8_05_05 <- plot_k2(k_sequences_filter8_05_05)

# alpha = 0.6 and beta = 0.4
k_sequences_filter8_06_04 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.6,
  beta = 0.4,
  mode ="sequence"
)
# Results
k_sequences_filter8_06_04_df <- k_sequences_filter8_06_04$df_results

# plot
plot_sequences_filter8_06_04 <- plot_k2(k_sequences_filter8_06_04)

# alpha = 0.7 and beta = 0.3
k_sequences_filter8_07_03 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.7,
  beta = 0.3,
  mode ="sequence"
)
# Results
k_sequences_filter8_07_03_df <- k_sequences_filter8_07_03$df_results

# plot
plot_sequences_filter8_07_03 <- plot_k2(k_sequences_filter8_07_03)

# alpha = 0.8 and beta = 0.2
k_sequences_filter8_08_02 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.8,
  beta = 0.2,
  mode ="sequence"
)
# Results
k_sequences_filter8_08_02_df <- k_sequences_filter8_08_02$df_results

# plot
plot_sequences_filter8_08_02 <- plot_k2(k_sequences_filter8_08_02)

# alpha = 0.9 and beta = 0.1
k_sequences_filter8_09_01 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.9,
  beta = 0.1,
  mode ="sequence"
)
# Results
k_sequences_filter8_09_01_df <- k_sequences_filter8_09_01$df_results

# plot
plot_sequences_filter8_09_01 <- plot_k2(k_sequences_filter8_09_01)

# alpha = 1 and beta = 0
k_sequences_filter8_1_0 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 1,
  beta = 0,
  mode ="sequence"
)
# Results
k_sequences_filter8_1_0_df <- k_sequences_filter8_1_0$df_results

# plot
plot_sequences_filter8_1_0 <- plot_k2(k_sequences_filter8_1_0)

# alpha = 0.4 and beta = 0.6
k_sequences_filter8_04_06 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.4,
  beta = 0.6,
  mode ="sequence"
)
# Results
k_sequences_filter8_04_06_df <- k_sequences_filter8_04_06$df_results

# plot
plot_sequences_filter8_04_06 <- plot_k2(k_sequences_filter8_04_06)

# alpha = 0.3 and beta = 0.7
k_sequences_filter8_03_07 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.3,
  beta = 0.7,
  mode ="sequence"
)
# Results
k_sequences_filter8_03_07_df <- k_sequences_filter8_03_07$df_results

# plot
plot_sequences_filter8_03_07 <- plot_k2(k_sequences_filter8_03_07)

# alpha = 0.2 and beta = 0.8
k_sequences_filter8_02_08 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.2,
  beta = 0.8,
  mode ="sequence"
)
# Results
k_sequences_filter8_02_08_df <- k_sequences_filter8_02_08$df_results

# plot
plot_sequences_filter8_02_08 <- plot_k2(k_sequences_filter8_02_08)

# alpha = 0.1 and beta = 0.9
k_sequences_filter8_01_09 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.1,
  beta = 0.9,
  mode ="sequence"
)
# Results
k_sequences_filter8_01_09_df <- k_sequences_filter8_01_09$df_results

# plot
plot_sequences_filter8_01_09 <- plot_k2(k_sequences_filter8_01_09)

# alpha = 0 and beta = 1
k_sequences_filter8_0_1 <- k_validation_pairwaise8(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0,
  beta = 1,
  mode ="sequence"
)
# Results
k_sequences_filter8_0_1_df <- k_sequences_filter8_0_1$df_results

# plot
plot_sequences_filter8_0_1 <- plot_k2(k_sequences_filter8_0_1)
```

```{r filter 9 (0.00045)}
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_especies_filter9_05_05 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.5,
  beta = 0.5,
  mode ="taxonomy"
)
# Results
k_especies_filter9_05_05_df <- k_especies_filter9_05_05$df_results

# plot
plot_especies_filter9_05_05 <- plot_k2(k_especies_filter9_05_05)

# alpha = 0.6 and beta = 0.4
k_especies_filter9_06_04 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.6,
  beta = 0.4,
  mode ="taxonomy"
)
# Results
k_especies_filter9_06_04_df <- k_especies_filter9_06_04$df_results

# plot
plot_especies_filter9_06_04 <- plot_k2(k_especies_filter9_06_04)

# alpha = 0.7 and beta = 0.3
k_especies_filter9_07_03 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.7,
  beta = 0.3,
  mode ="taxonomy"
)
# Results
k_especies_filter9_07_03_df <- k_especies_filter9_07_03$df_results

# plot
plot_especies_filter9_07_03 <- plot_k2(k_especies_filter9_07_03)

# alpha = 0.8 and beta = 0.2
k_especies_filter9_08_02 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.8,
  beta = 0.2,
  mode ="taxonomy"
)
# Results
k_especies_filter9_08_02_df <- k_especies_filter9_08_02$df_results

# plot
plot_especies_filter9_08_02 <- plot_k2(k_especies_filter9_08_02)

# alpha = 0.9 and beta = 0.1
k_especies_filter9_09_01 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.9,
  beta = 0.1,
  mode ="taxonomy"
)
# Results
k_especies_filter9_09_01_df <- k_especies_filter9_09_01$df_results

# plot
plot_especies_filter9_09_01 <- plot_k2(k_especies_filter9_09_01)

# alpha = 1 and beta = 0
k_especies_filter9_1_0 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 1,
  beta = 0,
  mode ="taxonomy"
)
# Results
k_especies_filter9_1_0_df <- k_especies_filter9_1_0$df_results

# plot
plot_especies_filter9_1_0 <- plot_k2(k_especies_filter9_1_0)

# alpha = 0.4 and beta = 0.6
k_especies_filter9_04_06 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.4,
  beta = 0.6,
  mode ="taxonomy"
)
# Results
k_especies_filter9_04_06_df <- k_especies_filter9_04_06$df_results

# plot
plot_especies_filter9_04_06 <- plot_k2(k_especies_filter9_04_06)

# alpha = 0.3 and beta = 0.7
k_especies_filter9_03_07 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.3,
  beta = 0.7,
  mode ="taxonomy"
)
# Results
k_especies_filter9_03_07_df <- k_especies_filter9_03_07$df_results

# plot
plot_especies_filter9_03_07 <- plot_k2(k_especies_filter9_03_07)

# alpha = 0.2 and beta = 0.8
k_especies_filter9_02_08 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.2,
  beta = 0.8,
  mode ="taxonomy"
)
# Results
k_especies_filter9_02_08_df <- k_especies_filter9_02_08$df_results

# plot
plot_especies_filter9_02_08 <- plot_k2(k_especies_filter9_02_08)

# alpha = 0.1 and beta = 0.9
k_especies_filter9_01_09 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.1,
  beta = 0.9,
  mode ="taxonomy"
)
# Results
k_especies_filter9_01_09_df <- k_especies_filter9_01_09$df_results

# plot
plot_especies_filter9_01_09 <- plot_k2(k_especies_filter9_01_09)

# alpha = 0 and beta = 1
k_especies_filter9_0_1 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0,
  beta = 1,
  mode ="taxonomy"
)
# Results
k_especies_filter9_0_1_df <- k_especies_filter9_0_1$df_results

# plot
plot_especies_filter9_0_1 <- plot_k2(k_especies_filter9_0_1)


#SEQUENCES APPROACH
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_sequences_filter9_05_05 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.5,
  beta = 0.5,
  mode ="sequence"
)
# Results
k_sequences_filter9_05_05_df <- k_sequences_filter9_05_05$df_results

# plot
plot_sequences_filter9_05_05 <- plot_k2(k_sequences_filter9_05_05)

# alpha = 0.6 and beta = 0.4
k_sequences_filter9_06_04 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.6,
  beta = 0.4,
  mode ="sequence"
)
# Results
k_sequences_filter9_06_04_df <- k_sequences_filter9_06_04$df_results

# plot
plot_sequences_filter9_06_04 <- plot_k2(k_sequences_filter9_06_04)

# alpha = 0.7 and beta = 0.3
k_sequences_filter9_07_03 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.7,
  beta = 0.3,
  mode ="sequence"
)
# Results
k_sequences_filter9_07_03_df <- k_sequences_filter9_07_03$df_results

# plot
plot_sequences_filter9_07_03 <- plot_k2(k_sequences_filter9_07_03)

# alpha = 0.8 and beta = 0.2
k_sequences_filter9_08_02 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.8,
  beta = 0.2,
  mode ="sequence"
)
# Results
k_sequences_filter9_08_02_df <- k_sequences_filter9_08_02$df_results

# plot
plot_sequences_filter9_08_02 <- plot_k2(k_sequences_filter9_08_02)

# alpha = 0.9 and beta = 0.1
k_sequences_filter9_09_01 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.9,
  beta = 0.1,
  mode ="sequence"
)
# Results
k_sequences_filter9_09_01_df <- k_sequences_filter9_09_01$df_results

# plot
plot_sequences_filter9_09_01 <- plot_k2(k_sequences_filter9_09_01)

# alpha = 1 and beta = 0
k_sequences_filter9_1_0 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 1,
  beta = 0,
  mode ="sequence"
)
# Results
k_sequences_filter9_1_0_df <- k_sequences_filter9_1_0$df_results

# plot
plot_sequences_filter9_1_0 <- plot_k2(k_sequences_filter9_1_0)

# alpha = 0.4 and beta = 0.6
k_sequences_filter9_04_06 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.4,
  beta = 0.6,
  mode ="sequence"
)
# Results
k_sequences_filter9_04_06_df <- k_sequences_filter9_04_06$df_results

# plot
plot_sequences_filter9_04_06 <- plot_k2(k_sequences_filter9_04_06)

# alpha = 0.3 and beta = 0.7
k_sequences_filter9_03_07 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.3,
  beta = 0.7,
  mode ="sequence"
)
# Results
k_sequences_filter9_03_07_df <- k_sequences_filter9_03_07$df_results

# plot
plot_sequences_filter9_03_07 <- plot_k2(k_sequences_filter9_03_07)

# alpha = 0.2 and beta = 0.8
k_sequences_filter9_02_08 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.2,
  beta = 0.8,
  mode ="sequence"
)
# Results
k_sequences_filter9_02_08_df <- k_sequences_filter9_02_08$df_results

# plot
plot_sequences_filter9_02_08 <- plot_k2(k_sequences_filter9_02_08)

# alpha = 0.1 and beta = 0.9
k_sequences_filter9_01_09 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.1,
  beta = 0.9,
  mode ="sequence"
)
# Results
k_sequences_filter9_01_09_df <- k_sequences_filter9_01_09$df_results

# plot
plot_sequences_filter9_01_09 <- plot_k2(k_sequences_filter9_01_09)

# alpha = 0 and beta = 1
k_sequences_filter9_0_1 <- k_validation_pairwaise9(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0,
  beta = 1,
  mode ="sequence"
)
# Results
k_sequences_filter9_0_1_df <- k_sequences_filter9_0_1$df_results

# plot
plot_sequences_filter9_0_1 <- plot_k2(k_sequences_filter9_0_1)
```

```{r filter 10 (0.0005)}
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_especies_filter10_05_05 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.5,
  beta = 0.5,
  mode ="taxonomy"
)
# Results
k_especies_filter10_05_05_df <- k_especies_filter10_05_05$df_results

# plot
plot_especies_filter10_05_05 <- plot_k2(k_especies_filter10_05_05)

# alpha = 0.6 and beta = 0.4
k_especies_filter10_06_04 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.6,
  beta = 0.4,
  mode ="taxonomy"
)
# Results
k_especies_filter10_06_04_df <- k_especies_filter10_06_04$df_results

# plot
plot_especies_filter10_06_04 <- plot_k2(k_especies_filter10_06_04)

# alpha = 0.7 and beta = 0.3
k_especies_filter10_07_03 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.7,
  beta = 0.3,
  mode ="taxonomy"
)
# Results
k_especies_filter10_07_03_df <- k_especies_filter10_07_03$df_results

# plot
plot_especies_filter10_07_03 <- plot_k2(k_especies_filter10_07_03)

# alpha = 0.8 and beta = 0.2
k_especies_filter10_08_02 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.8,
  beta = 0.2,
  mode ="taxonomy"
)
# Results
k_especies_filter10_08_02_df <- k_especies_filter10_08_02$df_results

# plot
plot_especies_filter10_08_02 <- plot_k2(k_especies_filter10_08_02)

# alpha = 0.9 and beta = 0.1
k_especies_filter10_09_01 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.9,
  beta = 0.1,
  mode ="taxonomy"
)
# Results
k_especies_filter10_09_01_df <- k_especies_filter10_09_01$df_results

# plot
plot_especies_filter10_09_01 <- plot_k2(k_especies_filter10_09_01)

# alpha = 1 and beta = 0
k_especies_filter10_1_0 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 1,
  beta = 0,
  mode ="taxonomy"
)
# Results
k_especies_filter10_1_0_df <- k_especies_filter10_1_0$df_results

# plot
plot_especies_filter10_1_0 <- plot_k2(k_especies_filter10_1_0)

# alpha = 0.4 and beta = 0.6
k_especies_filter10_04_06 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.4,
  beta = 0.6,
  mode ="taxonomy"
)
# Results
k_especies_filter10_04_06_df <- k_especies_filter10_04_06$df_results

# plot
plot_especies_filter10_04_06 <- plot_k2(k_especies_filter10_04_06)

# alpha = 0.3 and beta = 0.7
k_especies_filter10_03_07 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.3,
  beta = 0.7,
  mode ="taxonomy"
)
# Results
k_especies_filter10_03_07_df <- k_especies_filter10_03_07$df_results

# plot
plot_especies_filter10_03_07 <- plot_k2(k_especies_filter10_03_07)

# alpha = 0.2 and beta = 0.8
k_especies_filter10_02_08 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.2,
  beta = 0.8,
  mode ="taxonomy"
)
# Results
k_especies_filter10_02_08_df <- k_especies_filter10_02_08$df_results

# plot
plot_especies_filter10_02_08 <- plot_k2(k_especies_filter10_02_08)

# alpha = 0.1 and beta = 0.9
k_especies_filter10_01_09 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0.1,
  beta = 0.9,
  mode ="taxonomy"
)
# Results
k_especies_filter10_01_09_df <- k_especies_filter10_01_09$df_results

# plot
plot_especies_filter10_01_09 <- plot_k2(k_especies_filter10_01_09)

# alpha = 0 and beta = 1
k_especies_filter10_0_1 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_taxa,
  alpha = 0,
  beta = 1,
  mode ="taxonomy"
)
# Results
k_especies_filter10_0_1_df <- k_especies_filter10_0_1$df_results

# plot
plot_especies_filter10_0_1 <- plot_k2(k_especies_filter10_0_1)


#SEQUENCES APPROACH
# k for all weights and plot
# alpha = 0.5 and beta = 0.5
k_sequences_filter10_05_05 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.5,
  beta = 0.5,
  mode ="sequence"
)
# Results
k_sequences_filter10_05_05_df <- k_sequences_filter10_05_05$df_results

# plot
plot_sequences_filter10_05_05 <- plot_k2(k_sequences_filter10_05_05)

# alpha = 0.6 and beta = 0.4
k_sequences_filter10_06_04 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.6,
  beta = 0.4,
  mode ="sequence"
)
# Results
k_sequences_filter10_06_04_df <- k_sequences_filter10_06_04$df_results

# plot
plot_sequences_filter10_06_04 <- plot_k2(k_sequences_filter10_06_04)

# alpha = 0.7 and beta = 0.3
k_sequences_filter10_07_03 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.7,
  beta = 0.3,
  mode ="sequence"
)
# Results
k_sequences_filter10_07_03_df <- k_sequences_filter10_07_03$df_results

# plot
plot_sequences_filter10_07_03 <- plot_k2(k_sequences_filter10_07_03)

# alpha = 0.8 and beta = 0.2
k_sequences_filter10_08_02 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.8,
  beta = 0.2,
  mode ="sequence"
)
# Results
k_sequences_filter10_08_02_df <- k_sequences_filter10_08_02$df_results

# plot
plot_sequences_filter10_08_02 <- plot_k2(k_sequences_filter10_08_02)

# alpha = 0.9 and beta = 0.1
k_sequences_filter10_09_01 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.9,
  beta = 0.1,
  mode ="sequence"
)
# Results
k_sequences_filter10_09_01_df <- k_sequences_filter10_09_01$df_results

# plot
plot_sequences_filter10_09_01 <- plot_k2(k_sequences_filter10_09_01)

# alpha = 1 and beta = 0
k_sequences_filter10_1_0 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 1,
  beta = 0,
  mode ="sequence"
)
# Results
k_sequences_filter10_1_0_df <- k_sequences_filter10_1_0$df_results

# plot
plot_sequences_filter10_1_0 <- plot_k2(k_sequences_filter10_1_0)

# alpha = 0.4 and beta = 0.6
k_sequences_filter10_04_06 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.4,
  beta = 0.6,
  mode ="sequence"
)
# Results
k_sequences_filter10_04_06_df <- k_sequences_filter10_04_06$df_results

# plot
plot_sequences_filter10_04_06 <- plot_k2(k_sequences_filter10_04_06)

# alpha = 0.3 and beta = 0.7
k_sequences_filter10_03_07 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.3,
  beta = 0.7,
  mode ="sequence"
)
# Results
k_sequences_filter10_03_07_df <- k_sequences_filter10_03_07$df_results

# plot
plot_sequences_filter10_03_07 <- plot_k2(k_sequences_filter10_03_07)

# alpha = 0.2 and beta = 0.8
k_sequences_filter10_02_08 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.2,
  beta = 0.8,
  mode ="sequence"
)
# Results
k_sequences_filter10_02_08_df <- k_sequences_filter10_02_08$df_results

# plot
plot_sequences_filter10_02_08 <- plot_k2(k_sequences_filter10_02_08)

# alpha = 0.1 and beta = 0.9
k_sequences_filter10_01_09 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0.1,
  beta = 0.9,
  mode ="sequence"
)
# Results
k_sequences_filter10_01_09_df <- k_sequences_filter10_01_09$df_results

# plot
plot_sequences_filter10_01_09 <- plot_k2(k_sequences_filter10_01_09)

# alpha = 0 and beta = 1
k_sequences_filter10_0_1 <- k_validation_pairwaise10(
  OTU_table = OTU_table_filt_df,
  ground_truth = ground_truth_sequences,
  alpha = 0,
  beta = 1,
  mode ="sequence"
)
# Results
k_sequences_filter10_0_1_df <- k_sequences_filter10_0_1$df_results

# plot
plot_sequences_filter10_0_1 <- plot_k2(k_sequences_filter10_0_1)
```


```{r filter standard}
print(plot_sequences_standard_05_05)
print(plot_sequences_standard_06_04)
print(plot_sequences_standard_07_03)
print(plot_sequences_standard_08_02)
print(plot_sequences_standard_09_01)
print(plot_sequences_standard_1_0)
print(plot_sequences_standard_04_06)
print(plot_sequences_standard_03_07)
print(plot_sequences_standard_02_08)
print(plot_sequences_standard_01_09)
print(plot_sequences_standard_0_1)
```

```{r filter2}
print(plot_sequences_filter2_05_05)
print(plot_sequences_filter2_06_04)
print(plot_sequences_filter2_07_03)
print(plot_sequences_filter2_08_02)
print(plot_sequences_filter2_09_01)
print(plot_sequences_filter2_1_0)
print(plot_sequences_filter2_04_06)
print(plot_sequences_filter2_03_07)
print(plot_sequences_filter2_02_08)
print(plot_sequences_filter2_01_09)
print(plot_sequences_filter2_0_1)
```

```{r filter3}
print(plot_sequences_filter3_05_05)
print(plot_sequences_filter3_06_04)
print(plot_sequences_filter3_07_03)
print(plot_sequences_filter3_08_02)
print(plot_sequences_filter3_09_01)
print(plot_sequences_filter3_1_0)
print(plot_sequences_filter3_04_06)
print(plot_sequences_filter3_03_07)
print(plot_sequences_filter3_02_08)
print(plot_sequences_filter3_01_09)
print(plot_sequences_filter3_0_1)
```

```{r filter4}
print(plot_sequences_filter4_05_05)
print(plot_sequences_filter4_06_04)
print(plot_sequences_filter4_07_03)
print(plot_sequences_filter4_08_02)
print(plot_sequences_filter4_09_01)
print(plot_sequences_filter4_1_0)
print(plot_sequences_filter4_04_06)
print(plot_sequences_filter4_03_07)
print(plot_sequences_filter4_02_08)
print(plot_sequences_filter4_01_09)
print(plot_sequences_filter4_0_1)
```

```{r filter5}
print(plot_sequences_filter5_05_05)
print(plot_sequences_filter5_06_04)
print(plot_sequences_filter5_07_03)
print(plot_sequences_filter5_08_02)
print(plot_sequences_filter5_09_01)
print(plot_sequences_filter5_1_0)
print(plot_sequences_filter5_04_06)
print(plot_sequences_filter5_03_07)
print(plot_sequences_filter5_02_08)
print(plot_sequences_filter5_01_09)
print(plot_sequences_filter5_0_1)
```

```{r filter6}
print(plot_sequences_filter6_05_05)
print(plot_sequences_filter6_06_04)
print(plot_sequences_filter6_07_03)
print(plot_sequences_filter6_08_02)
print(plot_sequences_filter6_09_01)
print(plot_sequences_filter6_1_0)
print(plot_sequences_filter6_04_06)
print(plot_sequences_filter6_03_07)
print(plot_sequences_filter6_02_08)
print(plot_sequences_filter6_01_09)
print(plot_sequences_filter6_0_1)
```

```{r filter 7}
print(plot_sequences_filter7_05_05)
print(plot_sequences_filter7_06_04)
print(plot_sequences_filter7_07_03)
print(plot_sequences_filter7_08_02)
print(plot_sequences_filter7_09_01)
print(plot_sequences_filter7_1_0)
print(plot_sequences_filter7_04_06)
print(plot_sequences_filter7_03_07)
print(plot_sequences_filter7_02_08)
print(plot_sequences_filter7_01_09)
print(plot_sequences_filter7_0_1)
```

```{r filter8}
print(plot_sequences_filter8_05_05)
print(plot_sequences_filter8_06_04)
print(plot_sequences_filter8_07_03)
print(plot_sequences_filter8_08_02)
print(plot_sequences_filter8_09_01)
print(plot_sequences_filter8_1_0)
print(plot_sequences_filter8_04_06)
print(plot_sequences_filter8_03_07)
print(plot_sequences_filter8_02_08)
print(plot_sequences_filter8_01_09)
print(plot_sequences_filter8_0_1)
```

```{r filter9}
print(plot_sequences_filter9_05_05)
print(plot_sequences_filter9_06_04)
print(plot_sequences_filter9_07_03)
print(plot_sequences_filter9_08_02)
print(plot_sequences_filter9_09_01)
print(plot_sequences_filter9_1_0)
print(plot_sequences_filter9_04_06)
print(plot_sequences_filter9_03_07)
print(plot_sequences_filter9_02_08)
print(plot_sequences_filter9_01_09)
print(plot_sequences_filter9_0_1)
```

```{r filter10}
print(plot_sequences_filter10_05_05)
print(plot_sequences_filter10_06_04)
print(plot_sequences_filter10_07_03)
print(plot_sequences_filter10_08_02)
print(plot_sequences_filter10_09_01)
print(plot_sequences_filter10_1_0)
print(plot_sequences_filter10_04_06)
print(plot_sequences_filter10_03_07)
print(plot_sequences_filter10_02_08)
print(plot_sequences_filter10_01_09)
print(plot_sequences_filter10_0_1)
```

```{r filter standard species}
print(plot_especies_standard_05_05)
print(plot_especies_standard_06_04)
print(plot_especies_standard_07_03)
print(plot_especies_standard_08_02)
print(plot_especies_standard_09_01)
print(plot_especies_standard_1_0)
print(plot_especies_standard_04_06)
print(plot_especies_standard_03_07)
print(plot_especies_standard_02_08)
print(plot_especies_standard_01_09)
print(plot_especies_standard_0_1)
```

```{r filter2 species}
print(plot_especies_filter2_05_05)
print(plot_especies_filter2_06_04)
print(plot_especies_filter2_07_03)
print(plot_especies_filter2_08_02)
print(plot_especies_filter2_09_01)
print(plot_especies_filter2_1_0)
print(plot_especies_filter2_04_06)
print(plot_especies_filter2_03_07)
print(plot_especies_filter2_02_08)
print(plot_especies_filter2_01_09)
print(plot_especies_filter2_0_1)
```

```{r filter3 species}
print(plot_especies_filter3_05_05)
print(plot_especies_filter3_06_04)
print(plot_especies_filter3_07_03)
print(plot_especies_filter3_08_02)
print(plot_especies_filter3_09_01)
print(plot_especies_filter3_1_0)
print(plot_especies_filter3_04_06)
print(plot_especies_filter3_03_07)
print(plot_especies_filter3_02_08)
print(plot_especies_filter3_01_09)
print(plot_especies_filter3_0_1)
```

```{r filter4 species}
print(plot_especies_filter4_05_05)
print(plot_especies_filter4_06_04)
print(plot_especies_filter4_07_03)
print(plot_especies_filter4_08_02)
print(plot_especies_filter4_09_01)
print(plot_especies_filter4_1_0)
print(plot_especies_filter4_04_06)
print(plot_especies_filter4_03_07)
print(plot_especies_filter4_02_08)
print(plot_especies_filter4_01_09)
print(plot_especies_filter4_0_1)
```

```{r filter5 species }
print(plot_especies_filter5_05_05)
print(plot_especies_filter5_06_04)
print(plot_especies_filter5_07_03)
print(plot_especies_filter5_08_02)
print(plot_especies_filter5_09_01)
print(plot_especies_filter5_1_0)
print(plot_especies_filter5_04_06)
print(plot_especies_filter5_03_07)
print(plot_especies_filter5_02_08)
print(plot_especies_filter5_01_09)
print(plot_especies_filter5_0_1)
```

```{r filter6 species}
print(plot_especies_filter6_05_05)
print(plot_especies_filter6_06_04)
print(plot_especies_filter6_07_03)
print(plot_especies_filter6_08_02)
print(plot_especies_filter6_09_01)
print(plot_especies_filter6_1_0)
print(plot_especies_filter6_04_06)
print(plot_especies_filter6_03_07)
print(plot_especies_filter6_02_08)
print(plot_especies_filter6_01_09)
print(plot_especies_filter6_0_1)
```

```{r filter 7 species}
print(plot_especies_filter7_05_05)
print(plot_especies_filter7_06_04)
print(plot_especies_filter7_07_03)
print(plot_especies_filter7_08_02)
print(plot_especies_filter7_09_01)
print(plot_especies_filter7_1_0)
print(plot_especies_filter7_04_06)
print(plot_especies_filter7_03_07)
print(plot_especies_filter7_02_08)
print(plot_especies_filter7_01_09)
print(plot_especies_filter7_0_1)
```

```{r filter8 species}
print(plot_especies_filter8_05_05)
print(plot_especies_filter8_06_04)
print(plot_especies_filter8_07_03)
print(plot_especies_filter8_08_02)
print(plot_especies_filter8_09_01)
print(plot_especies_filter8_1_0)
print(plot_especies_filter8_04_06)
print(plot_especies_filter8_03_07)
print(plot_especies_filter8_02_08)
print(plot_especies_filter8_01_09)
print(plot_especies_filter8_0_1)
```

```{r filter9 species}
print(plot_especies_filter9_05_05)
print(plot_especies_filter9_06_04)
print(plot_especies_filter9_07_03)
print(plot_especies_filter9_08_02)
print(plot_especies_filter9_09_01)
print(plot_especies_filter9_1_0)
print(plot_especies_filter9_04_06)
print(plot_especies_filter9_03_07)
print(plot_especies_filter9_02_08)
print(plot_especies_filter9_01_09)
print(plot_especies_filter9_0_1)
```

```{r filter10 species}
print(plot_especies_filter10_05_05)
print(plot_especies_filter10_06_04)
print(plot_especies_filter10_07_03)
print(plot_especies_filter10_08_02)
print(plot_especies_filter10_09_01)
print(plot_especies_filter10_1_0)
print(plot_especies_filter10_04_06)
print(plot_especies_filter10_03_07)
print(plot_especies_filter10_02_08)
print(plot_especies_filter10_01_09)
print(plot_especies_filter10_0_1)
```